namespace KnightFrank.Antares.Dal.Seed
{
	using System;
	using System.Collections.Generic;
	using System.Data.Entity.Migrations;
	using System.Linq;

	using KnightFrank.Antares.Dal.Model;

    internal class DepartmentData
    {
		public static void Seed(KnightFrankContext context)
		{
			List<Country> countries = context.Country.ToList();

			SeedDepartment(context, countries);

			context.SaveChanges();
		}

		private static void SeedDepartment(KnightFrankContext context, List<Country> countries)
		{
			SeedDepartmentData(context, countries, "- - (INDIA)", "IN");
			SeedDepartmentData(context, countries, " Middle East - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "(AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "(BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "(CHINA)", "CN");
			SeedDepartmentData(context, countries, "(CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "(FRANCE)", "FR");
			SeedDepartmentData(context, countries, "(GERMANY)", "DE");
			SeedDepartmentData(context, countries, "(GREECE)", "GR");
			SeedDepartmentData(context, countries, "(HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "(INDIA)", "IN");
			SeedDepartmentData(context, countries, "(INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "(IRELAND)", "IE");
			SeedDepartmentData(context, countries, "(ITALY)", "IT");
			SeedDepartmentData(context, countries, "(KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "(NETHERLANDS)", "NL");
			SeedDepartmentData(context, countries, "(NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, countries, "(PORTUGAL)", "PT");
			SeedDepartmentData(context, countries, "(RWANDA)", "RW");
			SeedDepartmentData(context, countries, "(SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "(SPAIN)", "ES");
			SeedDepartmentData(context, countries, "(SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "(UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Aberdeen", "GB");
			SeedDepartmentData(context, countries, "Aberdeen - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Aberdeen Commercial", "GB");
			SeedDepartmentData(context, countries, "Aberdeen Residential Development", "GB");
			SeedDepartmentData(context, countries, "Abu Dhabi - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Accountant - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Accounts", "GB");
			SeedDepartmentData(context, countries, "Accounts - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Accounts - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Accounts - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Accounts Dept. - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "ADM - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Admin - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Admin - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Administration - - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Administration - (CAMBODIA)", "KH");
			SeedDepartmentData(context, countries, "Administration - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Administration - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Administration - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Administration - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Administration - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Administration - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Administration - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Administration - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Administration & Account - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Advisory - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory Corporate & Support - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory, H&L and Retail - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory-CAT - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory-CET - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Advisory-Research - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Africa", "GB");
			SeedDepartmentData(context, countries, "Agency - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Agency - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Agency - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Agency - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Agency - (NIGERIA)", "NG");
			SeedDepartmentData(context, countries, "Agency - Marketing & Leasing / Global Corpotate Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Agency & Consultancy - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Agency & Professional Advisory Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Agency Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Agency Office - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Agency Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Aldgate", "GB");
			SeedDepartmentData(context, countries, "Aldgate Lettings", "GB");
			SeedDepartmentData(context, countries, "Amend This For A Correct Department Code", "GB");
			SeedDepartmentData(context, countries, "AMS - Property Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "AMS / Charter Hall - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Amsterdam - Broersma - (NETHERLANDS)", "NL");
			SeedDepartmentData(context, countries, "Ascot", "GB");
			SeedDepartmentData(context, countries, "Ascot Lettings", "GB");
			SeedDepartmentData(context, countries, "Asia Pacific - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Asia Pacific - Global Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Asia Pacific Desk", "GB");
			SeedDepartmentData(context, countries, "Asia Pacific International Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asian Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Assest Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management & Investment Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Asset Management Services, FM Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management Services, ISPT - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management Services, North Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management Services, Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Asset Management Services, Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Auction - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Australia Managing Director, Sydney North Shore - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Automotive", "GB");
			SeedDepartmentData(context, countries, "Back Office - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Badminton", "GB");
			SeedDepartmentData(context, countries, "Bahamas - Damianos Realty - (BAHAMAS)", "BS");
			SeedDepartmentData(context, countries, "Bali - Elite Havens - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Bali & Lombok - Elite Havens - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Bangkok - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Barbados - Bajan Services - (BARBADOS)", "BB");
			SeedDepartmentData(context, countries, "Barcelona - Lucas Fox - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Barnes", "GB");
			SeedDepartmentData(context, countries, "Basingstoke", "GB");
			SeedDepartmentData(context, countries, "Bath", "GB");
			SeedDepartmentData(context, countries, "Bath New Homes", "GB");
			SeedDepartmentData(context, countries, "Bath Res Dev", "GB");
			SeedDepartmentData(context, countries, "Bath Residential Development", "GB");
			SeedDepartmentData(context, countries, "Beaconsfield", "GB");
			SeedDepartmentData(context, countries, "Beaconsfield Lettings", "GB");
			SeedDepartmentData(context, countries, "Belgravia", "GB");
			SeedDepartmentData(context, countries, "Belgravia Lettings", "GB");
			SeedDepartmentData(context, countries, "Belsize Park", "GB");
			SeedDepartmentData(context, countries, "Belsize Park Lettings", "GB");
			SeedDepartmentData(context, countries, "Belsize Park Sales", "GB");
			SeedDepartmentData(context, countries, "Berkhamsted", "GB");
			SeedDepartmentData(context, countries, "Berlin - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Bermuda - Rego Realtors - (BERMUDA)", "BM");
			SeedDepartmentData(context, countries, "Birmingham Commercial", "GB");
			SeedDepartmentData(context, countries, "Birmingham Hotels", "GB");
			SeedDepartmentData(context, countries, "Birmingham Land / Agency", "GB");
			SeedDepartmentData(context, countries, "Birmingham Land and Agency", "GB");
			SeedDepartmentData(context, countries, "Birmingham Lettings", "GB");
			SeedDepartmentData(context, countries, "Birmingham Residential", "GB");
			SeedDepartmentData(context, countries, "Birmingham Residential Development", "GB");
			SeedDepartmentData(context, countries, "Birmingham Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Birmingham Residential Development Vals", "GB");
			SeedDepartmentData(context, countries, "Bishops Stortford", "GB");
			SeedDepartmentData(context, countries, "Blenkin and Co", "GB");
			SeedDepartmentData(context, countries, "Bonnieux, Provence - Janssens Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Bristol", "GB");
			SeedDepartmentData(context, countries, "Bristol Commercial", "GB");
			SeedDepartmentData(context, countries, "Bristol Residential", "GB");
			SeedDepartmentData(context, countries, "Bristol Residential Development", "GB");
			SeedDepartmentData(context, countries, "Bristol Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Brussels - Immobiliere Le Lion - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Building Consultancy", "GB");
			SeedDepartmentData(context, countries, "Building Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Building Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Building Consultancy Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Building Surveying", "GB");
			SeedDepartmentData(context, countries, "Building Surveying.", "GB");
			SeedDepartmentData(context, countries, "Business Development", "GB");
			SeedDepartmentData(context, countries, "Business Development - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Business Intelligence Unit", "GB");
			SeedDepartmentData(context, countries, "Business Rates", "GB");
			SeedDepartmentData(context, countries, "Business Service - (CAMBODIA)", "KH");
			SeedDepartmentData(context, countries, "Business Service - (MALAWI)", "MW");
			SeedDepartmentData(context, countries, "Business Services - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Business Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Business Services - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Business Services Graduate", "GB");
			SeedDepartmentData(context, countries, "Business Services.", "GB");
			SeedDepartmentData(context, countries, "Business Space, Industrial - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Business Support - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Business Support - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Buying Solution - Country", "GB");
			SeedDepartmentData(context, countries, "Buying Solution - London", "GB");
			SeedDepartmentData(context, countries, "BVI - Smiths Gore - (VIRGIN ISLANDS)", "VG");
			SeedDepartmentData(context, countries, "Canary Wharf Lettings", "GB");
			SeedDepartmentData(context, countries, "Canary Wharf Residential", "GB");
			SeedDepartmentData(context, countries, "Cape Town - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, countries, "Capiltal Markets - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Capital Market - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Capital Market - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Capital Markets", "GB");
			SeedDepartmentData(context, countries, "Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Capital Markets - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Capital Markets - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Capital Markets - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Capital Markets - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Capital Markets - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Capital Markets - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Capital Markets - (MALAYSIA)", "MY");
			SeedDepartmentData(context, countries, "Capital Markets - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Capital Markets - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Capital Markets - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Capital Markets - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Capital Markets - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Capital Markets - Commercial Sales - (NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, countries, "Capital Markets & Residential Sales - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Capital Markets & Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Capital Markets / Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Capital Markets and Commercial Valuations - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Capital Markets, and Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Capital Markets, Asian Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Captial Transaction Group - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Cardiff Commercial", "GB");
			SeedDepartmentData(context, countries, "Cardiff Residential Development", "GB");
			SeedDepartmentData(context, countries, "Casselden and Urban Workshop - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Cayman - IRG - (CAYMAN ISLANDS)", "KY");
			SeedDepartmentData(context, countries, "Central Algarve - Prime Properties - (PORTUGAL)", "PT");
			SeedDepartmentData(context, countries, "Central Events", "GB");
			SeedDepartmentData(context, countries, "Central London Research", "GB");
			SeedDepartmentData(context, countries, "Central London Tenant Rep", "GB");
			SeedDepartmentData(context, countries, "Central Residential Development", "GB");
			SeedDepartmentData(context, countries, "Central Service - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Central Services - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Chamonix - Mountain Base - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Charter Hall - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Chelsea", "GB");
			SeedDepartmentData(context, countries, "Chelsea Barracks", "GB");
			SeedDepartmentData(context, countries, "Chelsea Lettings", "GB");
			SeedDepartmentData(context, countries, "Cheltenham", "GB");
			SeedDepartmentData(context, countries, "China Desk", "GB");
			SeedDepartmentData(context, countries, "China Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Chiswick ", "GB");
			SeedDepartmentData(context, countries, "Chiswick Lettings", "GB");
			SeedDepartmentData(context, countries, "Chiswick Sales", "GB");
			SeedDepartmentData(context, countries, "Cirencester", "GB");
			SeedDepartmentData(context, countries, "Cirencester Lettings [old]", "GB");
			SeedDepartmentData(context, countries, "Cirencester Residential Development", "GB");
			SeedDepartmentData(context, countries, "City", "GB");
			SeedDepartmentData(context, countries, "City and East Residential Development", "GB");
			SeedDepartmentData(context, countries, "Clapham", "GB");
			SeedDepartmentData(context, countries, "Clapham Lettings", "GB");
			SeedDepartmentData(context, countries, "Clarges", "GB");
			SeedDepartmentData(context, countries, "Client Services", "GB");
			SeedDepartmentData(context, countries, "Cobham", "GB");
			SeedDepartmentData(context, countries, "Cobham Lettings", "GB");
			SeedDepartmentData(context, countries, "Comercial Valuations", "GB");
			SeedDepartmentData(context, countries, "Comm Vals", "GB");
			SeedDepartmentData(context, countries, "Commecial - (MALAWI)", "MW");
			SeedDepartmentData(context, countries, "Commecial/ Residential - (CAMBODIA)", "KH");
			SeedDepartmentData(context, countries, "Commecial/ Residential - (MALAWI)", "MW");
			SeedDepartmentData(context, countries, "Commercial", "GB");
			SeedDepartmentData(context, countries, "Commercial - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Commercial - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Commercial - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Commercial - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Commercial & Compliance - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Commercial & Industrial Agency - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial & Residential - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Commercial / Global Capital markets - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Commercial Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Commercial Agency - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Commercial Agency - (TANZANIA)", "TZ");
			SeedDepartmentData(context, countries, "Commercial Agency - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Commercial Agency / Leasing (Landlord & Tenant Rep) - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Agency / Leassing (Landlord & Tenant Rep) - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Agency Tenant Representation - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Commercial Agency/Leasing; Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Agnecy - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Commercial and Retail Sale - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Commercial Asset Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Development Consultancy - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Division - Head", "GB");
			SeedDepartmentData(context, countries, "Commercial Graduate", "GB");
			SeedDepartmentData(context, countries, "Commercial Investment", "GB");
			SeedDepartmentData(context, countries, "Commercial Investment - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Commercial Investment / Capital Markets - 1 - (BAHRAIN)", "BH");
			SeedDepartmentData(context, countries, "Commercial Investment / Capital Markets - Portfolios - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Commercial Investments", "GB");
			SeedDepartmentData(context, countries, "Commercial Leasing", "GB");
			SeedDepartmentData(context, countries, "Commercial Leasing - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Commercial Lettings - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Commercial Pool", "GB");
			SeedDepartmentData(context, countries, "Commercial Professional Consultancy - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Commercial Property, Facilities & Asset Management - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Sales & Leasing - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Commercial Sales & Leasing (North) - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Sales & Leasing, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Sales & Office Leasing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Sales, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Commercial Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Commercial Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Commercial Services - Landlord - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Commercial Services - Tenant - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Commercial Valuation - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Commercial Valuations", "GB");
			SeedDepartmentData(context, countries, "Commercial Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Commercial Valuations - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Commercial Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Commerical - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Communication/PR/Marketing/Agency/Support staff - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Compliances - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Construction - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Consultancy - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Consultancy & Research - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Consultancy -(IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Consultants", "GB");
			SeedDepartmentData(context, countries, "Conversion", "GB");
			SeedDepartmentData(context, countries, "Coordinator - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Corporate - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Corporate - Business Development - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate - Marketing & Public Relations - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate - Senior Management - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate Business Development - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate Commercial - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate Communications", "GB");
			SeedDepartmentData(context, countries, "Corporate Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Corporate Finance", "GB");
			SeedDepartmentData(context, countries, "Corporate Finance / Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Corporate Finance/ Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Corporate Public Relations", "GB");
			SeedDepartmentData(context, countries, "Corporate Real Estate", "GB");
			SeedDepartmentData(context, countries, "Corporate Service - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Corporate Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Corporate -Sr. Management - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Corporate Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Country - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Country Department", "GB");
			SeedDepartmentData(context, countries, "Country House Consultancy", "GB");
			SeedDepartmentData(context, countries, "Country User", "GB");
			SeedDepartmentData(context, countries, "Courchevel - CIMALPES - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Crans Montana - Altitude Immobilier - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Creative Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Croatia - Sanda Marisuc - (CROATIA)", "HR");
			SeedDepartmentData(context, countries, "CTG-Transaction Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Database Management", "GB");
			SeedDepartmentData(context, countries, "Development & Agricultural Land and Industrial - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Development & Agricultural Land and Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Development Consultancy - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Development Consultancy & Research - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Development Land - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Development Land, Retail, Industrial & Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Digital", "GB");
			SeedDepartmentData(context, countries, "Docklands Commercial", "GB");
			SeedDepartmentData(context, countries, "Domestic Hotels", "GB");
			SeedDepartmentData(context, countries, "Dordogne - Classic French Homes - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Dublin - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Dulwich Sales", "GB");
			SeedDepartmentData(context, countries, "Dulwich Village", "GB");
			SeedDepartmentData(context, countries, "East Anglia Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Edinburgh Commercial", "GB");
			SeedDepartmentData(context, countries, "Edinburgh Residential Development", "GB");
			SeedDepartmentData(context, countries, "Edinburgh Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "EMEA Tenant Representation", "GB");
			SeedDepartmentData(context, countries, "Energy", "GB");
			SeedDepartmentData(context, countries, "Energy", "GB");
			SeedDepartmentData(context, countries, "Enterprise Services, Information Technology - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Esher", "GB");
			SeedDepartmentData(context, countries, "Esher Lettings", "GB");
			SeedDepartmentData(context, countries, "Euro Commercial Valuations User", "GB");
			SeedDepartmentData(context, countries, "Europe", "GB");
			SeedDepartmentData(context, countries, "Europe (new)", "GB");
			SeedDepartmentData(context, countries, "Europe (old)", "GB");
			SeedDepartmentData(context, countries, "European Department [old]", "GB");
			SeedDepartmentData(context, countries, "European Tenant Rep", "GB");
			SeedDepartmentData(context, countries, "European Tenant Representation", "GB");
			SeedDepartmentData(context, countries, "European Valuations", "GB");
			SeedDepartmentData(context, countries, "Events, Hospitality and Charity", "GB");
			SeedDepartmentData(context, countries, "Evian - Laurent Guerineau Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Executive Assistant, Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Executive Chairman - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Executive Management & Valuation - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Exeter Commercial", "GB");
			SeedDepartmentData(context, countries, "Exeter Residential", "GB");
			SeedDepartmentData(context, countries, "Exeter Residential Development", "GB");
			SeedDepartmentData(context, countries, "Expertises - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Facilities Management - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Facilities Management - Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Facilities Management  Services (Core Team) - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Facilities Management - Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Facilities Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Facilities Management-Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Facility Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Farms, Estates & Residential Agency - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Finanace - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Finance - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Finance - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Finance - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Finance - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Finance - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Finance - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Finance - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Finance & Property Management - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Finance and Strategy", "GB");
			SeedDepartmentData(context, countries, "Finance, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Financial Controller Town Planning - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Financial Services France [old]", "GB");
			SeedDepartmentData(context, countries, "Florence - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Florida - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, countries, "FM- Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "FMS - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "FMS - Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "FMS (Core) - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Franchise - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Frankfurt - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Fulham", "GB");
			SeedDepartmentData(context, countries, "Fulham Lettings", "GB");
			SeedDepartmentData(context, countries, "Gascony - Purslow's Gascony - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "GCS", "GB");
			SeedDepartmentData(context, countries, "GCS - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "GCS - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Geelong Market Square - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "General Management - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "General Mangement - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "General Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Geneva - Naef Prestige - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Geneva - Partner Real Estate - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Genova, Liguria - IIN Liguria - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Glasgow", "GB");
			SeedDepartmentData(context, countries, "Glasgow Commercial", "GB");
			SeedDepartmentData(context, countries, "Global Capital Market - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Global Capital Market/ Acquisitions and Disposals - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Global Capital Markets", "GB");
			SeedDepartmentData(context, countries, "Global Capital Markets - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Global Corporate Service - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Global Corporate Services", "GB");
			SeedDepartmentData(context, countries, "Global Corporate Services - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Global Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Global Corporate Services, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Graduate", "GB");
			SeedDepartmentData(context, countries, "Graduates", "GB");
			SeedDepartmentData(context, countries, "Graduates - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Graduates - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Greek Islands - Ionian International - (GREECE)", "GR");
			SeedDepartmentData(context, countries, "Grimaud - Skillington Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Group Chairman", "GB");
			SeedDepartmentData(context, countries, "Group Director GCS, Project Management & Building Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Group Managing Director - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "GSC - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Gstaad - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Guildford", "GB");
			SeedDepartmentData(context, countries, "Guildford Lettings", "GB");
			SeedDepartmentData(context, countries, "Guildford Residential Development", "GB");
			SeedDepartmentData(context, countries, "Hampstead", "GB");
			SeedDepartmentData(context, countries, "Hampstead Lettings", "GB");
			SeedDepartmentData(context, countries, "Hanoi - (VIETNAM)", "VN");
			SeedDepartmentData(context, countries, "Harrogate", "GB");
			SeedDepartmentData(context, countries, "Haslemere", "GB");
			SeedDepartmentData(context, countries, "Head of Capital Markets - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of International Project Marketing - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of Land Advisory Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Head of Landlord Project Services, China - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of Lettings", "GB");
			SeedDepartmentData(context, countries, "Head of Mortgage Valuation (Special Properties) - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Head of Portfolio Optimisation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Head of Research & Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of Tenant Representative, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Head of Valuation & Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Head of Valuation & Professional Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Head Office", "GB");
			SeedDepartmentData(context, countries, "Healthcare", "GB");
			SeedDepartmentData(context, countries, "Henley", "GB");
			SeedDepartmentData(context, countries, "Henley Lettings", "GB");
			SeedDepartmentData(context, countries, "Hereford", "GB");
			SeedDepartmentData(context, countries, "Ho Chi Minh - (VIETNAM)", "VN");
			SeedDepartmentData(context, countries, "Ho Chi Minh - Vietnam - (VIETNAM)", "ES");
			SeedDepartmentData(context, countries, "Holland Park Villas", "GB");
			SeedDepartmentData(context, countries, "Hong Kong", "GB");
			SeedDepartmentData(context, countries, "Horsham", "GB");
			SeedDepartmentData(context, countries, "Hospitality & Leisure - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Hotels", "GB");
			SeedDepartmentData(context, countries, "Hotels - Birmingham", "GB");
			SeedDepartmentData(context, countries, "Hotels - Exeter", "GB");
			SeedDepartmentData(context, countries, "Hotels - Leeds", "GB");
			SeedDepartmentData(context, countries, "Hotels - West Country", "GB");
			SeedDepartmentData(context, countries, "Hotels - Winchester", "GB");
			SeedDepartmentData(context, countries, "HR - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "HR & Admin - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "HR & Administraction - (RWANDA)", "RW");
			SeedDepartmentData(context, countries, "HR & Administraction - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "HR and Administration - (RWANDA)", "RW");
			SeedDepartmentData(context, countries, "Human Resources", "GB");
			SeedDepartmentData(context, countries, "Human Resources - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Human Resources - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Human Resources - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Human Resources, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Hungerford", "GB");
			SeedDepartmentData(context, countries, "Hungerford - Estate Office", "GB");
			SeedDepartmentData(context, countries, "Hyde Park", "GB");
			SeedDepartmentData(context, countries, "Hyde Park Lettings", "GB");
			SeedDepartmentData(context, countries, "Hyde Park Sales", "GB");
			SeedDepartmentData(context, countries, "Ibiza - Villa Contact - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "India", "GB");
			SeedDepartmentData(context, countries, "Industrial - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Industrial - (NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, countries, "Industrial - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Industrial - Business Space - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Industrial - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Industrial & Asset Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Industrial & Logistics - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Industrial & Retail Agency - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Industrial, Business Space - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Industrial, Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Industry department - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Information Centre", "GB");
			SeedDepartmentData(context, countries, "Information Technology", "GB");
			SeedDepartmentData(context, countries, "Information Technology - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Information Technology - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Information Technology - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Information Technology - APAC - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Information Technology, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Information Technology, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Institutional Sales - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Institutional Sales, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Integrated Development Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "International Hotels [old]", "GB");
			SeedDepartmentData(context, countries, "International Project Marketing", "GB");
			SeedDepartmentData(context, countries, "International Project Marketing - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "International Project Marketing - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "International Residential", "GB");
			SeedDepartmentData(context, countries, "International Residential - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "International Residential Development", "GB");
			SeedDepartmentData(context, countries, "Investment", "GB");
			SeedDepartmentData(context, countries, "Investment - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Investment - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Investment - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Investment - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Investment and Lettings Management", "GB");
			SeedDepartmentData(context, countries, "Investment Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Investment Lettings and Management", "GB");
			SeedDepartmentData(context, countries, "Investment Lettings and Management", "GB");
			SeedDepartmentData(context, countries, "Investment, Valuation, Residential - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Investment, Valuation, Residential - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Investments", "GB");
			SeedDepartmentData(context, countries, "Investments - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Investments - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Investments - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Investments - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Investments & Asset Receivership - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Investments and Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "IPM - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Islington", "GB");
			SeedDepartmentData(context, countries, "Islington Lettings", "GB");
			SeedDepartmentData(context, countries, "IT", "GB");
			SeedDepartmentData(context, countries, "IT - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "IT - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "IT - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "IT - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "IT DEPARTMENT - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "IT Dept. - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "IT Projects", "GB");
			SeedDepartmentData(context, countries, "IT Services", "GB");
			SeedDepartmentData(context, countries, "Jumby Bay - Jumby Bay Island - (ANTIGUA AND BARBUDA)", "AG");
			SeedDepartmentData(context, countries, "Junior Negotiator - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Kensington", "GB");
			SeedDepartmentData(context, countries, "Kensington Lettings", "GB");
			SeedDepartmentData(context, countries, "KF Finance - Home Counties", "GB");
			SeedDepartmentData(context, countries, "KF Investment Management", "GB");
			SeedDepartmentData(context, countries, "KF Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "KFEM - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Kings Cross Lettings", "GB");
			SeedDepartmentData(context, countries, "Kingston upon Thames", "GB");
			SeedDepartmentData(context, countries, "Knight Frank Asset Management - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Knight Frank Expertises - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Knight Frank Finance", "GB");
			SeedDepartmentData(context, countries, "Knight Frank Global Wealth", "GB");
			SeedDepartmentData(context, countries, "Knight Frank Partner Alliance - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Knight Frank Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Knight Frank Valuations Canberra - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Knightsbridge", "GB");
			SeedDepartmentData(context, countries, "Knightsbridge Lettings", "GB");
			SeedDepartmentData(context, countries, "Kowloon Commercial Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Lake Como - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Land - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Land Advisory Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Land Agency - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Landlord Project Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Landlord Representation, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "LATELIER - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Lauder", "GB");
			SeedDepartmentData(context, countries, "Lausanne, Switzerland - Naef Prestige - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Lease Advisory - Landlord / Tenant - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Leasehold Reform", "GB");
			SeedDepartmentData(context, countries, "Leeds", "GB");
			SeedDepartmentData(context, countries, "Leeds Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Leeds Residential Development Vals", "GB");
			SeedDepartmentData(context, countries, "Legal - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Legal Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Leisure", "GB");
			SeedDepartmentData(context, countries, "Leisure [old]", "GB");
			SeedDepartmentData(context, countries, "Lettings Operations", "GB");
			SeedDepartmentData(context, countries, "Liverpool Commercial", "GB");
			SeedDepartmentData(context, countries, "Liverpool Residential Development", "GB");
			SeedDepartmentData(context, countries, "Liverpool Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Liverpool Residential Development Vals", "GB");
			SeedDepartmentData(context, countries, "Logistics & Industrial - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Logistics & Industrial Agency", "GB");
			SeedDepartmentData(context, countries, "Logistics and Industrial Agency", "GB");
			SeedDepartmentData(context, countries, "London Residential Development", "GB");
			SeedDepartmentData(context, countries, "London Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "London Residential Head", "GB");
			SeedDepartmentData(context, countries, "Los Angeles - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, countries, "LPS - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Lucca - Ser.Imm", "BL");
			SeedDepartmentData(context, countries, "Lucca - Ser.Imm - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Lugano - Emerald Casa - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Lymington", "GB");
			SeedDepartmentData(context, countries, "Madrid - Residential - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Mainland Greece - Ploumis Sotiropoulos - (GREECE)", "GR");
			SeedDepartmentData(context, countries, "Malaysia - (MALAYSIA)", "MY");
			SeedDepartmentData(context, countries, "Mallorca - Mallorca Gold - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Malta - Belair - (MALTA)", "MT");
			SeedDepartmentData(context, countries, "Management - (BOTSWANA)", "BW");
			SeedDepartmentData(context, countries, "Management - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Management - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, countries, "Management - (TANZANIA)", "TZ");
			SeedDepartmentData(context, countries, "Management Support Division - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Manager- Training - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Managing Director, Sydney - North Shore - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Manchester City Centre Sales", "GB");
			SeedDepartmentData(context, countries, "Manchester Commercial", "GB");
			SeedDepartmentData(context, countries, "Manchester Residential Development", "GB");
			SeedDepartmentData(context, countries, "Manchester Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Manchester Residential Development Vals", "GB");
			SeedDepartmentData(context, countries, "Mapping", "GB");
			SeedDepartmentData(context, countries, "Marbella - Diana Morales Properties - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Marine", "GB");
			SeedDepartmentData(context, countries, "Marketing", "GB");
			SeedDepartmentData(context, countries, "Marketing - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Marketing - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Marketing - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Marketing & Administration - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Marketing & Communications - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Marketing & Communications - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Marketing & Communications - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Marketing & Communications - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Marketing & Communications - Agency - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Marketing & Communications, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Marketing & Internal Projects - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Marketing &PR - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Marketing and Communications", "GB");
			SeedDepartmentData(context, countries, "Marketing and Communications - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Marketing and Communications - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Marketing and Communications - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Marketing NSW - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Marylebone", "GB");
			SeedDepartmentData(context, countries, "Marylebone Lettings", "GB");
			SeedDepartmentData(context, countries, "Mauritius - MJ Property Solutions - (MAURITIUS)", "MU");
			SeedDepartmentData(context, countries, "Mayfair", "GB");
			SeedDepartmentData(context, countries, "Mayfair Lettings", "GB");
			SeedDepartmentData(context, countries, "Megeve - Agence Boan - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Meribel - CIMALPES - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Michael de Pelet", "GB");
			SeedDepartmentData(context, countries, "Middle East", "GB");
			SeedDepartmentData(context, countries, "Middle Eastern Desk", "GB");
			SeedDepartmentData(context, countries, "Middle Eastern Desk - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Milan - Case di Campagna - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Milton Keynes Residential Development", "GB");
			SeedDepartmentData(context, countries, "Mixed Use and Residential Asset Management", "GB");
			SeedDepartmentData(context, countries, "Monaco - PVN Real Estate Investments - (MONACO)", "MC");
			SeedDepartmentData(context, countries, "Monpazier - La Porte Property - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Mortgage Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Morzine - Morzine Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Mougins - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "MSD - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Munich - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Munich - Riedel Immobilien - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Mustique - The Mustique Company - (SAINT VINCENT AND THE GRENADINES)", "VC");
			SeedDepartmentData(context, countries, "National Offices", "GB");
			SeedDepartmentData(context, countries, "Neuchatel, Switzerland - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "New Homes", "GB");
			SeedDepartmentData(context, countries, "New Homes - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "New Lettings Department", "GB");
			SeedDepartmentData(context, countries, "New York - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, countries, "Newcastle Commercial", "GB");
			SeedDepartmentData(context, countries, "Newcastle Promise", "GB");
			SeedDepartmentData(context, countries, "Newcastle Residential Development", "GB");
			SeedDepartmentData(context, countries, "Newcastle Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Newcastle Residential Development Vals", "GB");
			SeedDepartmentData(context, countries, "Newmark Global Corporate Services", "GB");
			SeedDepartmentData(context, countries, "NL Real Estate - (NETHERLANDS)", "NL");
			SeedDepartmentData(context, countries, "Northern Residential Development", "GB");
			SeedDepartmentData(context, countries, "Notting Hill", "GB");
			SeedDepartmentData(context, countries, "Notting Hill Lettings", "GB");
			SeedDepartmentData(context, countries, "Nottingham Residential Development", "GB");
			SeedDepartmentData(context, countries, "Occupier Solutions", "GB");
			SeedDepartmentData(context, countries, "Occupier Solutions - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Occupier Solutions Group - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Office - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Office & Industrial - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Office Administration - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Office Administration - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Office Agency - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Office Agency - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Office Agency - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Office and Industrial-IAS - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Office and Industrial-LRG - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Office and Industrial-OSG - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Office Leasing & Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Office Leasing I Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Office Leasing, North Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Office Manager - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Offices - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Offices - (ROMANIA)", "RO");
			SeedDepartmentData(context, countries, "One Hyde Park", "GB");
			SeedDepartmentData(context, countries, "One Kensington Gardens", "GB");
			SeedDepartmentData(context, countries, "One Tower Bridge Lettings", "GB");
			SeedDepartmentData(context, countries, "Operations - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Operations - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Operations & Risk", "GB");
			SeedDepartmentData(context, countries, "Operations and Risk", "GB");
			SeedDepartmentData(context, countries, "OSG - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Oslo - Ek - (NORWAY)", "NO");
			SeedDepartmentData(context, countries, "Overseas - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Oxford", "GB");
			SeedDepartmentData(context, countries, "Oxford Lettings", "GB");
			SeedDepartmentData(context, countries, "Oxford Residential Development", "GB");
			SeedDepartmentData(context, countries, "Paris - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Paris - Belles Demeures de France - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Partner - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Pension Fund", "GB");
			SeedDepartmentData(context, countries, "Planning", "GB");
			SeedDepartmentData(context, countries, "Planning - Regions", "GB");
			SeedDepartmentData(context, countries, "PM- Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "PM- Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "PMC - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "PM-Corporate - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "PMS - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "PMS-Site - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Portfolio Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Portfolio Optimisation - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Portfolio Optimisation, Global Corporate Services, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Post Room", "GB");
			SeedDepartmentData(context, countries, "Prime Central London", "GB");
			SeedDepartmentData(context, countries, "Prime Central London Developments", "GB");
			SeedDepartmentData(context, countries, "Prime Central London Team", "GB");
			SeedDepartmentData(context, countries, "Prime New Homes", "GB");
			SeedDepartmentData(context, countries, "Print Room", "GB");
			SeedDepartmentData(context, countries, "Professional Consultancy & Valuation - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Professional Services - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Professional Services - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Project & Building Consultancy", "GB");
			SeedDepartmentData(context, countries, "Project Management - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Project Management - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, countries, "Project Management and Building Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Project Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Project Management Services (Non-Site) - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Project Management Services (SITE) - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Project Marketing - (MALAYSIA)", "MY");
			SeedDepartmentData(context, countries, "Promise - PAM", "GB");
			SeedDepartmentData(context, countries, "Promise - RAM", "GB");
			SeedDepartmentData(context, countries, "Promise RAM", "GB");
			SeedDepartmentData(context, countries, "Property Accounting Services - Accounts Payable - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Property Accounting Services - National - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Property Accouting Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Property Asset Management", "GB");
			SeedDepartmentData(context, countries, "Property Management - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Property Management - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, countries, "Property Management - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Property Management - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Property Management - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Property Management - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Property Management - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Property Management - (TANZANIA)", "TZ");
			SeedDepartmentData(context, countries, "Property Management - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Property Management - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Property Management - Commercial (UGANDA) - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Property Management - Retail - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Property Management & Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Property Management & Asset Receivership - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Property Management Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Property Management Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, countries, "Property Management Estate - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Property management Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Property Management Villa - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Property Management, Residential - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Property Managemeny Retails - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Public Sector", "GB");
			SeedDepartmentData(context, countries, "Queens Park", "GB");
			SeedDepartmentData(context, countries, "Queen's Park", "GB");
			SeedDepartmentData(context, countries, "Queen's Park Lettings", "GB");
			SeedDepartmentData(context, countries, "Queens Park Sales", "GB");
			SeedDepartmentData(context, countries, "Reception - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Reception - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Reception - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Reception and Security", "GB");
			SeedDepartmentData(context, countries, "Receptionist - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Regional Investment Team Central", "GB");
			SeedDepartmentData(context, countries, "Registry", "GB");
			SeedDepartmentData(context, countries, "Renewables", "GB");
			SeedDepartmentData(context, countries, "Rent management Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Res Vals and Consultancy - Country", "GB");
			SeedDepartmentData(context, countries, "Research", "GB");
			SeedDepartmentData(context, countries, "Research - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Research - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Research - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Research - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Research & Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Research & Consultancy, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Research & Operations - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Research & Valuation - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Research and Consultancy - (CAMBODIA)", "KH");
			SeedDepartmentData(context, countries, "Research and Consulting - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Research and Development Consultancy - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Residental Research", "GB");
			SeedDepartmentData(context, countries, "Residential", "GB");
			SeedDepartmentData(context, countries, "Residential - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Residential - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Residential - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Residential - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Residential - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Residential - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Residential - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Residential - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, countries, "Residential - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Residential - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Residential - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Residential - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Residential - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, countries, "Residential - IPM - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Residential & Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential (Leasing) - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Residential (Prime Sales) - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Residential Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Residential Agency - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential Agency - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Residential Agency - (TANZANIA)", "TZ");
			SeedDepartmentData(context, countries, "Residential Asset Management", "GB");
			SeedDepartmentData(context, countries, "Residential Business Development Unit", "GB");
			SeedDepartmentData(context, countries, "Residential Capital Markets", "GB");
			SeedDepartmentData(context, countries, "Residential Channel - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential City - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Residential Corporate Services", "GB");
			SeedDepartmentData(context, countries, "Residential Country Business ", "GB");
			SeedDepartmentData(context, countries, "Residential Country Business - Head", "GB");
			SeedDepartmentData(context, countries, "Residential Development", "GB");
			SeedDepartmentData(context, countries, "Residential Development Capital Markets", "GB");
			SeedDepartmentData(context, countries, "Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Residential Developments - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential Division - Head", "GB");
			SeedDepartmentData(context, countries, "Residential Division Head", "GB");
			SeedDepartmentData(context, countries, "Residential Graduate", "GB");
			SeedDepartmentData(context, countries, "Residential Graduates", "GB");
			SeedDepartmentData(context, countries, "Residential International - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Residential Investment and International Project Marketing", "GB");
			SeedDepartmentData(context, countries, "Residential IPM - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential Lettings Accounts", "GB");
			SeedDepartmentData(context, countries, "Residential Lettings Head", "GB");
			SeedDepartmentData(context, countries, "Residential Lettings Investments", "GB");
			SeedDepartmentData(context, countries, "Residential Lettings IPM", "GB");
			SeedDepartmentData(context, countries, "Residential Lettings Management", "GB");
			SeedDepartmentData(context, countries, "Residential London Head", "GB");
			SeedDepartmentData(context, countries, "Residential Milan Office - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Residential Prime Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Residential Project Marketing - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential Project Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Residential Property Managemenr - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential Property Management Wharf One & Two - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential Research", "GB");
			SeedDepartmentData(context, countries, "Residential Sale", "GB");
			SeedDepartmentData(context, countries, "Residential Sale - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Residential Sales - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Residential Sales - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Residential sales - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Residential Sales - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Residential Valuation and Consultancy- Country", "GB");
			SeedDepartmentData(context, countries, "Residential Valuation and Consultancy- London", "GB");
			SeedDepartmentData(context, countries, "Residential, Asia Pacific - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Resodential - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "resres - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Rest of US - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, countries, "Restructuring and Recoveries", "GB");
			SeedDepartmentData(context, countries, "Restructuring and Recovery", "GB");
			SeedDepartmentData(context, countries, "Retail", "GB");
			SeedDepartmentData(context, countries, "Retail - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Retail - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Retail - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Retail - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Retail Agency", "GB");
			SeedDepartmentData(context, countries, "Retail Agency - (INDIA)", "IN");
			SeedDepartmentData(context, countries, "Retail Agency - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Retail Asset Management - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Retail Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Retail Services and Asset Management - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Retail/Property Management - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Richmond", "GB");
			SeedDepartmentData(context, countries, "Richmond Lettings", "GB");
			SeedDepartmentData(context, countries, "Riverside", "GB");
			SeedDepartmentData(context, countries, "Riverside Lettings", "GB");
			SeedDepartmentData(context, countries, "Riverside Sales", "GB");
			SeedDepartmentData(context, countries, "RL - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Rome - Immobili di Prestigio - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Royal Wharf", "GB");
			SeedDepartmentData(context, countries, "RS Prime Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Rural Consultancy", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy - Bishops Stortford", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy - Cotswolds", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy Bishops Stortford", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy Bristol", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy Cotswolds", "GB");
			SeedDepartmentData(context, countries, "Rural Consultancy Solent", "GB");
			SeedDepartmentData(context, countries, "Russia Desk", "GB");
			SeedDepartmentData(context, countries, "Rutley Capital Partners", "GB");
			SeedDepartmentData(context, countries, "Sales - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Sales & Leasing - (MALAYSIA)", "MY");
			SeedDepartmentData(context, countries, "Sales & Leasing, South Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Sanremo, Liguria - Liguria Homes", "BL");
			SeedDepartmentData(context, countries, "Sanremo, Liguria - Liguria Homes - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "SAP Project Team / HR", "GB");
			SeedDepartmentData(context, countries, "Sardinia - Immobiliare Brunati - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Sarteano - Tuscany Inside Out - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Scotland Res Dev Vals [old]", "GB");
			SeedDepartmentData(context, countries, "Scotland Residential", "GB");
			SeedDepartmentData(context, countries, "Scotland Residential - Lauder", "GB");
			SeedDepartmentData(context, countries, "Scotland Residential Development", "GB");
			SeedDepartmentData(context, countries, "Scotland Residential Development [old]", "GB");
			SeedDepartmentData(context, countries, "Scotland Residential Development Consultancy", "GB");
			SeedDepartmentData(context, countries, "Secretariat and Pensions", "GB");
			SeedDepartmentData(context, countries, "Senior Executive Team - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Senior Partner", "GB");
			SeedDepartmentData(context, countries, "Sevenoaks", "GB");
			SeedDepartmentData(context, countries, "Sevenoaks Residential Development", "GB");
			SeedDepartmentData(context, countries, "Shanghai", "GB");
			SeedDepartmentData(context, countries, "Sheffield Residential Development", "GB");
			SeedDepartmentData(context, countries, "Sherborne", "GB");
			SeedDepartmentData(context, countries, "Sicily - thinkSicily - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Solent", "GB");
			SeedDepartmentData(context, countries, "Solent Residential Development", "GB");
			SeedDepartmentData(context, countries, "Sotogrande - Holmes Sotogrande - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "South Africa - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, countries, "South Asia Desk", "GB");
			SeedDepartmentData(context, countries, "South East Offices", "GB");
			SeedDepartmentData(context, countries, "South Kensingtion Lettings", "GB");
			SeedDepartmentData(context, countries, "South Kensington", "GB");
			SeedDepartmentData(context, countries, "South Kensington Lettings", "GB");
			SeedDepartmentData(context, countries, "South Kensington Sales", "GB");
			SeedDepartmentData(context, countries, "South Sydney Agency - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "South Sydney Sales and Leasing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "South Sydney, Industrial - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "South West Residential Development", "GB");
			SeedDepartmentData(context, countries, "Southampton Residential Development", "GB");
			SeedDepartmentData(context, countries, "St Barts - Sibarth Real Estate", "BL");
			SeedDepartmentData(context, countries, "St Barts - Sibarth Real Estate - (ST BARTS)", "BL");
			SeedDepartmentData(context, countries, "St Johns Wood", "GB");
			SeedDepartmentData(context, countries, "St Johns Wood Lettings", "GB");
			SeedDepartmentData(context, countries, "St Remy de Provence - Janssens Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Stow On The Wold", "GB");
			SeedDepartmentData(context, countries, "Strategic Cons & Public Sector", "GB");
			SeedDepartmentData(context, countries, "Strategic Consulting - (RUSSIA)", "RU");
			SeedDepartmentData(context, countries, "Strategic Occupier Transactions", "GB");
			SeedDepartmentData(context, countries, "Stratford", "GB");
			SeedDepartmentData(context, countries, "Stratford Lettings", "GB");
			SeedDepartmentData(context, countries, "Stratford New Homes", "GB");
			SeedDepartmentData(context, countries, "Stratford Residential Development", "GB");
			SeedDepartmentData(context, countries, "Stratford Residential Development New Homes", "GB");
			SeedDepartmentData(context, countries, "Student Program - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Student Program, NSW - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Student Property", "GB");
			SeedDepartmentData(context, countries, "Student Property Residential Development", "GB");
			SeedDepartmentData(context, countries, "Support - (HONG KONG)", "HK");
			SeedDepartmentData(context, countries, "Support - (INDONESIA)", "ID");
			SeedDepartmentData(context, countries, "Sustainability & Energy", "GB");
			SeedDepartmentData(context, countries, "Sustainability & Energy Consultancy", "GB");
			SeedDepartmentData(context, countries, "Sutton Coldfield", "GB");
			SeedDepartmentData(context, countries, "Sydney Commercial ( Asian Markets) - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Taiwan - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Tax Department", "GB");
			SeedDepartmentData(context, countries, "Telephone Room", "GB");
			SeedDepartmentData(context, countries, "Tenancy Management", "GB");
			SeedDepartmentData(context, countries, "Tenant Representation, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Test Department", "GB");
			SeedDepartmentData(context, countries, "Thames Gateway", "GB");
			SeedDepartmentData(context, countries, "Thames Gateway", "GB");
			SeedDepartmentData(context, countries, "The Buying Solution - Country", "GB");
			SeedDepartmentData(context, countries, "The Buying Solution - London", "GB");
			SeedDepartmentData(context, countries, "The City", "GB");
			SeedDepartmentData(context, countries, "Third-Party USA - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, countries, "Tower Bridge", "GB");
			SeedDepartmentData(context, countries, "Tower Bridge Lettings", "GB");
			SeedDepartmentData(context, countries, "Tower Bridge Sales", "GB");
			SeedDepartmentData(context, countries, "Tunbridge Wells", "GB");
			SeedDepartmentData(context, countries, "Umbria - Abode - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "US Alliance Development", "GB");
			SeedDepartmentData(context, countries, "Val d'Isere - Agence Val d'Isere - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Valbonne - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Valuation - (BOTSWANA)", "BW");
			SeedDepartmentData(context, countries, "Valuation - (CHINA)", "CN");
			SeedDepartmentData(context, countries, "Valuation - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Valuation - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Valuation - (SINGAPORE)", "SG");
			SeedDepartmentData(context, countries, "Valuation - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Valuation - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Valuation & Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Valuation & Consultancy - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Valuation & Research - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Valuation and Consultancy - (THAILAND)", "TH");
			SeedDepartmentData(context, countries, "Valuation Consultancy - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Valuations - (FRANCE)", "FR");
			SeedDepartmentData(context, countries, "Valuations - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Valuations - (IRELAND)", "IE");
			SeedDepartmentData(context, countries, "Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Valuations - (MALAYSIA)", "MY");
			SeedDepartmentData(context, countries, "Valuations - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Valuations - (PORTUGAL)", "PT");
			SeedDepartmentData(context, countries, "Valuations - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, countries, "Valuations - (SPAIN)", "ES");
			SeedDepartmentData(context, countries, "Valuations - (TANZANIA)", "TZ");
			SeedDepartmentData(context, countries, "Valuations - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Valuations - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, countries, "Valuations - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, countries, "Valuations - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, countries, "Valuations & Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Valuations & Research - (KENYA)", "KE");
			SeedDepartmentData(context, countries, "Valuations and Professional Services - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, countries, "Valuations QLD - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, countries, "Valuations, Agency, Research & Consultancy, Investment - (CAMBODIA)", "KH");
			SeedDepartmentData(context, countries, "Valuations/Property Management - (POLAND)", "PL");
			SeedDepartmentData(context, countries, "Valuations/Sales - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, countries, "Valuer - (UGANDA)", "UG");
			SeedDepartmentData(context, countries, "Vancouver - Dexter Realty - (CANADA)", "CA");
			SeedDepartmentData(context, countries, "Venice - Venice Real Estate - (ITALY)", "IT");
			SeedDepartmentData(context, countries, "Verbier - Guinnard Immobilier SA - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Vienna - OTTO Immobilien - (AUSTRIA)", "AT");
			SeedDepartmentData(context, countries, "Villars - Regie Turrian SA - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, countries, "Virginia Water", "GB");
			SeedDepartmentData(context, countries, "Vision", "GB");
			SeedDepartmentData(context, countries, "Wandsworth", "GB");
			SeedDepartmentData(context, countries, "Wandsworth Lettings", "GB");
			SeedDepartmentData(context, countries, "Wapping", "GB");
			SeedDepartmentData(context, countries, "Wapping Lettings", "GB");
			SeedDepartmentData(context, countries, "Waterfront", "GB");
			SeedDepartmentData(context, countries, "Web site", "GB");
			SeedDepartmentData(context, countries, "West Country Healthcare", "GB");
			SeedDepartmentData(context, countries, "West Country Hotels", "GB");
			SeedDepartmentData(context, countries, "West End Agency", "GB");
			SeedDepartmentData(context, countries, "West End Capital Markets", "GB");
			SeedDepartmentData(context, countries, "West End Development", "GB");
			SeedDepartmentData(context, countries, "West End Investment", "GB");
			SeedDepartmentData(context, countries, "West End Investments", "GB");
			SeedDepartmentData(context, countries, "West End Office", "GB");
			SeedDepartmentData(context, countries, "West End Offices", "GB");
			SeedDepartmentData(context, countries, "Western Algarve - Sadler's Properties - (PORTUGAL)", "PT");
			SeedDepartmentData(context, countries, "Western Residential Development", "GB");
			SeedDepartmentData(context, countries, "Westminster City Council", "GB");
			SeedDepartmentData(context, countries, "Westminster City Council Team", "GB");
			SeedDepartmentData(context, countries, "Wimbledon", "GB");
			SeedDepartmentData(context, countries, "Wimbledon Lettings", "GB");
			SeedDepartmentData(context, countries, "Winchester", "GB");
			SeedDepartmentData(context, countries, "Worcester", "GB");
			SeedDepartmentData(context, countries, "Worcester Residential Development", "GB");
			SeedDepartmentData(context, countries, "Workplace Consultancy", "GB");
			SeedDepartmentData(context, countries, "Yorkshire Commercial", "GB");
			SeedDepartmentData(context, countries, "Yorkshire Residential Development", "GB");
			SeedDepartmentData(context, countries, "Zurich - Ginesta Immobilien - (SWITZERLAND)", "CH");
		}

		private static void SeedDepartmentData(KnightFrankContext context, IEnumerable<Country> countries, string name, string countryCode)
		{
			var department = new Department
			{
				Name = name,
				CountryId = GetCountryIdByCode(countries, countryCode)
			};

			context.Department.AddOrUpdate(x => x.Name, department);
		}

		private static Guid GetCountryIdByCode(IEnumerable<Country> countries, string countryCode)
		{
			Country country = countries.FirstOrDefault(c => c.IsoCode == countryCode);

			return country?.Id ?? default(Guid);
		}
	}
}