namespace KnightFrank.Antares.Dal.Seed
{
	using System;
	using System.Data.Entity.Migrations;
	using System.Linq;

	using KnightFrank.Antares.Dal.Model;

    internal class DepartmentData
    {
		public static void Seed(KnightFrankContext context)
	    {
			SeedDepartment(context);
		}

		private static void SeedDepartment(KnightFrankContext context)
		{
			SeedDepartmentData(context, "- - (INDIA)", "IN");
			SeedDepartmentData(context, " Middle East - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "(AUSTRALIA)", "AU");
			SeedDepartmentData(context, "(BELGIUM)", "BE");
			SeedDepartmentData(context, "(CHINA)", "CN");
			SeedDepartmentData(context, "(CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "(FRANCE)", "FR");
			SeedDepartmentData(context, "(GERMANY)", "DE");
			SeedDepartmentData(context, "(GREECE)", "GR");
			SeedDepartmentData(context, "(HONG KONG)", "HK");
			SeedDepartmentData(context, "(INDIA)", "IN");
			SeedDepartmentData(context, "(INDONESIA)", "ID");
			SeedDepartmentData(context, "(IRELAND)", "IE");
			SeedDepartmentData(context, "(ITALY)", "IT");
			SeedDepartmentData(context, "(KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "(NETHERLANDS)", "NL");
			SeedDepartmentData(context, "(NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, "(PORTUGAL)", "PT");
			SeedDepartmentData(context, "(RWANDA)", "RW");
			SeedDepartmentData(context, "(SINGAPORE)", "SG");
			SeedDepartmentData(context, "(SPAIN)", "ES");
			SeedDepartmentData(context, "(SWITZERLAND)", "CH");
			SeedDepartmentData(context, "(UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Aberdeen", "GB");
			SeedDepartmentData(context, "Aberdeen - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Aberdeen Commercial", "GB");
			SeedDepartmentData(context, "Aberdeen Residential Development", "GB");
			SeedDepartmentData(context, "Abu Dhabi - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Accountant - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Accounts", "GB");
			SeedDepartmentData(context, "Accounts - (GERMANY)", "DE");
			SeedDepartmentData(context, "Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, "Accounts - (SPAIN)", "ES");
			SeedDepartmentData(context, "Accounts - (UGANDA)", "UG");
			SeedDepartmentData(context, "Accounts Dept. - (INDIA)", "IN");
			SeedDepartmentData(context, "ADM - (THAILAND)", "TH");
			SeedDepartmentData(context, "Admin - (INDIA)", "IN");
			SeedDepartmentData(context, "Admin - (KENYA)", "KE");
			SeedDepartmentData(context, "Administration - - (THAILAND)", "TH");
			SeedDepartmentData(context, "Administration - (CAMBODIA)", "KH");
			SeedDepartmentData(context, "Administration - (CHINA)", "CN");
			SeedDepartmentData(context, "Administration - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Administration - (FRANCE)", "FR");
			SeedDepartmentData(context, "Administration - (INDIA)", "IN");
			SeedDepartmentData(context, "Administration - (IRELAND)", "IE");
			SeedDepartmentData(context, "Administration - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Administration - (THAILAND)", "TH");
			SeedDepartmentData(context, "Administration - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Administration & Account - (THAILAND)", "TH");
			SeedDepartmentData(context, "Advisory - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory Corporate & Support - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory, H&L and Retail - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory-CAT - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory-CET - (INDIA)", "IN");
			SeedDepartmentData(context, "Advisory-Research - (INDIA)", "IN");
			SeedDepartmentData(context, "Africa", "GB");
			SeedDepartmentData(context, "Agency - (CHINA)", "CN");
			SeedDepartmentData(context, "Agency - (FRANCE)", "FR");
			SeedDepartmentData(context, "Agency - (GERMANY)", "DE");
			SeedDepartmentData(context, "Agency - (ITALY)", "IT");
			SeedDepartmentData(context, "Agency - (NIGERIA)", "NG");
			SeedDepartmentData(context, "Agency - Marketing & Leasing / Global Corpotate Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Agency & Consultancy - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Agency & Professional Advisory Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Agency Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Agency Office - (SPAIN)", "ES");
			SeedDepartmentData(context, "Agency Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, "Aldgate", "GB");
			SeedDepartmentData(context, "Aldgate Lettings", "GB");
			SeedDepartmentData(context, "Amend This For A Correct Department Code", "GB");
			SeedDepartmentData(context, "AMS - Property Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "AMS / Charter Hall - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Amsterdam - Broersma - (NETHERLANDS)", "NL");
			SeedDepartmentData(context, "Ascot", "GB");
			SeedDepartmentData(context, "Ascot Lettings", "GB");
			SeedDepartmentData(context, "Asia Pacific - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Asia Pacific - Global Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Asia Pacific Desk", "GB");
			SeedDepartmentData(context, "Asia Pacific International Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asian Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Assest Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management & Investment Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Asset Management Services, FM Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management Services, ISPT - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management Services, North Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management Services, Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Asset Management Services, Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Auction - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Australia Managing Director, Sydney North Shore - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Automotive", "GB");
			SeedDepartmentData(context, "Back Office - (POLAND)", "PL");
			SeedDepartmentData(context, "Badminton", "GB");
			SeedDepartmentData(context, "Bahamas - Damianos Realty - (BAHAMAS)", "BS");
			SeedDepartmentData(context, "Bali - Elite Havens - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Bali & Lombok - Elite Havens - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Bangkok - (THAILAND)", "TH");
			SeedDepartmentData(context, "Barbados - Bajan Services - (BARBADOS)", "BB");
			SeedDepartmentData(context, "Barcelona - Lucas Fox - (SPAIN)", "ES");
			SeedDepartmentData(context, "Barnes", "GB");
			SeedDepartmentData(context, "Basingstoke", "GB");
			SeedDepartmentData(context, "Bath", "GB");
			SeedDepartmentData(context, "Bath New Homes", "GB");
			SeedDepartmentData(context, "Bath Res Dev", "GB");
			SeedDepartmentData(context, "Bath Residential Development", "GB");
			SeedDepartmentData(context, "Beaconsfield", "GB");
			SeedDepartmentData(context, "Beaconsfield Lettings", "GB");
			SeedDepartmentData(context, "Belgravia", "GB");
			SeedDepartmentData(context, "Belgravia Lettings", "GB");
			SeedDepartmentData(context, "Belsize Park", "GB");
			SeedDepartmentData(context, "Belsize Park Lettings", "GB");
			SeedDepartmentData(context, "Belsize Park Sales", "GB");
			SeedDepartmentData(context, "Berkhamsted", "GB");
			SeedDepartmentData(context, "Berlin - (GERMANY)", "DE");
			SeedDepartmentData(context, "Bermuda - Rego Realtors - (BERMUDA)", "BM");
			SeedDepartmentData(context, "Birmingham Commercial", "GB");
			SeedDepartmentData(context, "Birmingham Hotels", "GB");
			SeedDepartmentData(context, "Birmingham Land / Agency", "GB");
			SeedDepartmentData(context, "Birmingham Land and Agency", "GB");
			SeedDepartmentData(context, "Birmingham Lettings", "GB");
			SeedDepartmentData(context, "Birmingham Residential", "GB");
			SeedDepartmentData(context, "Birmingham Residential Development", "GB");
			SeedDepartmentData(context, "Birmingham Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Birmingham Residential Development Vals", "GB");
			SeedDepartmentData(context, "Bishops Stortford", "GB");
			SeedDepartmentData(context, "Blenkin and Co", "GB");
			SeedDepartmentData(context, "Bonnieux, Provence - Janssens Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, "Bristol", "GB");
			SeedDepartmentData(context, "Bristol Commercial", "GB");
			SeedDepartmentData(context, "Bristol Residential", "GB");
			SeedDepartmentData(context, "Bristol Residential Development", "GB");
			SeedDepartmentData(context, "Bristol Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Brussels - Immobiliere Le Lion - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Building Consultancy", "GB");
			SeedDepartmentData(context, "Building Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, "Building Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Building Consultancy Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, "Building Surveying", "GB");
			SeedDepartmentData(context, "Building Surveying.", "GB");
			SeedDepartmentData(context, "Business Development", "GB");
			SeedDepartmentData(context, "Business Development - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Business Intelligence Unit", "GB");
			SeedDepartmentData(context, "Business Rates", "GB");
			SeedDepartmentData(context, "Business Service - (CAMBODIA)", "KH");
			SeedDepartmentData(context, "Business Service - (MALAWI)", "MW");
			SeedDepartmentData(context, "Business Services - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Business Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Business Services - (SPAIN)", "ES");
			SeedDepartmentData(context, "Business Services Graduate", "GB");
			SeedDepartmentData(context, "Business Services.", "GB");
			SeedDepartmentData(context, "Business Space, Industrial - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Business Support - (INDIA)", "IN");
			SeedDepartmentData(context, "Business Support - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Buying Solution - Country", "GB");
			SeedDepartmentData(context, "Buying Solution - London", "GB");
			SeedDepartmentData(context, "BVI - Smiths Gore - (VIRGIN ISLANDS)", "VG");
			SeedDepartmentData(context, "Canary Wharf Lettings", "GB");
			SeedDepartmentData(context, "Canary Wharf Residential", "GB");
			SeedDepartmentData(context, "Cape Town - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, "Capiltal Markets - (ITALY)", "IT");
			SeedDepartmentData(context, "Capital Market - (FRANCE)", "FR");
			SeedDepartmentData(context, "Capital Market - (ITALY)", "IT");
			SeedDepartmentData(context, "Capital Markets", "GB");
			SeedDepartmentData(context, "Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Capital Markets - (CHINA)", "CN");
			SeedDepartmentData(context, "Capital Markets - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Capital Markets - (GERMANY)", "DE");
			SeedDepartmentData(context, "Capital Markets - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Capital Markets - (INDIA)", "IN");
			SeedDepartmentData(context, "Capital Markets - (ITALY)", "IT");
			SeedDepartmentData(context, "Capital Markets - (MALAYSIA)", "MY");
			SeedDepartmentData(context, "Capital Markets - (POLAND)", "PL");
			SeedDepartmentData(context, "Capital Markets - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Capital Markets - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Capital Markets - (SPAIN)", "ES");
			SeedDepartmentData(context, "Capital Markets - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Capital Markets - Commercial Sales - (NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, "Capital Markets & Residential Sales - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Capital Markets & Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, "Capital Markets / Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, "Capital Markets and Commercial Valuations - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Capital Markets, and Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Capital Markets, Asian Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Captial Transaction Group - (INDIA)", "IN");
			SeedDepartmentData(context, "Cardiff Commercial", "GB");
			SeedDepartmentData(context, "Cardiff Residential Development", "GB");
			SeedDepartmentData(context, "Casselden and Urban Workshop - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Cayman - IRG - (CAYMAN ISLANDS)", "KY");
			SeedDepartmentData(context, "Central Algarve - Prime Properties - (PORTUGAL)", "PT");
			SeedDepartmentData(context, "Central Events", "GB");
			SeedDepartmentData(context, "Central London Research", "GB");
			SeedDepartmentData(context, "Central London Tenant Rep", "GB");
			SeedDepartmentData(context, "Central Residential Development", "GB");
			SeedDepartmentData(context, "Central Service - (FRANCE)", "FR");
			SeedDepartmentData(context, "Central Services - (FRANCE)", "FR");
			SeedDepartmentData(context, "Chamonix - Mountain Base - (FRANCE)", "FR");
			SeedDepartmentData(context, "Charter Hall - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Chelsea", "GB");
			SeedDepartmentData(context, "Chelsea Barracks", "GB");
			SeedDepartmentData(context, "Chelsea Lettings", "GB");
			SeedDepartmentData(context, "Cheltenham", "GB");
			SeedDepartmentData(context, "China Desk", "GB");
			SeedDepartmentData(context, "China Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Chiswick ", "GB");
			SeedDepartmentData(context, "Chiswick Lettings", "GB");
			SeedDepartmentData(context, "Chiswick Sales", "GB");
			SeedDepartmentData(context, "Cirencester", "GB");
			SeedDepartmentData(context, "Cirencester Lettings [old]", "GB");
			SeedDepartmentData(context, "Cirencester Residential Development", "GB");
			SeedDepartmentData(context, "City", "GB");
			SeedDepartmentData(context, "City and East Residential Development", "GB");
			SeedDepartmentData(context, "Clapham", "GB");
			SeedDepartmentData(context, "Clapham Lettings", "GB");
			SeedDepartmentData(context, "Clarges", "GB");
			SeedDepartmentData(context, "Client Services", "GB");
			SeedDepartmentData(context, "Cobham", "GB");
			SeedDepartmentData(context, "Cobham Lettings", "GB");
			SeedDepartmentData(context, "Comercial Valuations", "GB");
			SeedDepartmentData(context, "Comm Vals", "GB");
			SeedDepartmentData(context, "Commecial - (MALAWI)", "MW");
			SeedDepartmentData(context, "Commecial/ Residential - (CAMBODIA)", "KH");
			SeedDepartmentData(context, "Commecial/ Residential - (MALAWI)", "MW");
			SeedDepartmentData(context, "Commercial", "GB");
			SeedDepartmentData(context, "Commercial - (CHINA)", "CN");
			SeedDepartmentData(context, "Commercial - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Commercial - (KENYA)", "KE");
			SeedDepartmentData(context, "Commercial - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Commercial & Compliance - (INDIA)", "IN");
			SeedDepartmentData(context, "Commercial & Industrial Agency - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial & Residential - (KENYA)", "KE");
			SeedDepartmentData(context, "Commercial / Global Capital markets - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Commercial Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Commercial Agency - (POLAND)", "PL");
			SeedDepartmentData(context, "Commercial Agency - (TANZANIA)", "TZ");
			SeedDepartmentData(context, "Commercial Agency - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Commercial Agency / Leasing (Landlord & Tenant Rep) - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Agency / Leassing (Landlord & Tenant Rep) - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Agency Tenant Representation - (POLAND)", "PL");
			SeedDepartmentData(context, "Commercial Agency/Leasing; Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Agnecy - (POLAND)", "PL");
			SeedDepartmentData(context, "Commercial and Retail Sale - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Commercial Asset Management - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Development Consultancy - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Division - Head", "GB");
			SeedDepartmentData(context, "Commercial Graduate", "GB");
			SeedDepartmentData(context, "Commercial Investment", "GB");
			SeedDepartmentData(context, "Commercial Investment - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Commercial Investment / Capital Markets - 1 - (BAHRAIN)", "BH");
			SeedDepartmentData(context, "Commercial Investment / Capital Markets - Portfolios - (ITALY)", "IT");
			SeedDepartmentData(context, "Commercial Investments", "GB");
			SeedDepartmentData(context, "Commercial Leasing", "GB");
			SeedDepartmentData(context, "Commercial Leasing - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Commercial Lettings - (KENYA)", "KE");
			SeedDepartmentData(context, "Commercial Pool", "GB");
			SeedDepartmentData(context, "Commercial Professional Consultancy - (FRANCE)", "FR");
			SeedDepartmentData(context, "Commercial Property, Facilities & Asset Management - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Sales & Leasing - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Commercial Sales & Leasing (North) - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Sales & Leasing, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Sales & Office Leasing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Sales, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Commercial Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Commercial Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Commercial Services - Landlord - (CHINA)", "CN");
			SeedDepartmentData(context, "Commercial Services - Tenant - (CHINA)", "CN");
			SeedDepartmentData(context, "Commercial Valuation - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Valuation - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Commercial Valuations", "GB");
			SeedDepartmentData(context, "Commercial Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Commercial Valuations - (GERMANY)", "DE");
			SeedDepartmentData(context, "Commercial Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, "Commerical - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Communication/PR/Marketing/Agency/Support staff - (ITALY)", "IT");
			SeedDepartmentData(context, "Compliances - (INDIA)", "IN");
			SeedDepartmentData(context, "Construction - (INDIA)", "IN");
			SeedDepartmentData(context, "Consultancy - (SPAIN)", "ES");
			SeedDepartmentData(context, "Consultancy & Research - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Consultancy -(IRELAND)", "IE");
			SeedDepartmentData(context, "Consultants", "GB");
			SeedDepartmentData(context, "Conversion", "GB");
			SeedDepartmentData(context, "Coordinator - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Corporate - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Corporate - Business Development - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate - Marketing & Public Relations - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate - Senior Management - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate Business Development - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate Commercial - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate Communications", "GB");
			SeedDepartmentData(context, "Corporate Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Corporate Finance", "GB");
			SeedDepartmentData(context, "Corporate Finance / Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Corporate Finance/ Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Corporate Public Relations", "GB");
			SeedDepartmentData(context, "Corporate Real Estate", "GB");
			SeedDepartmentData(context, "Corporate Service - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Corporate Services - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Corporate -Sr. Management - (INDIA)", "IN");
			SeedDepartmentData(context, "Corporate Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Country - (IRELAND)", "IE");
			SeedDepartmentData(context, "Country Department", "GB");
			SeedDepartmentData(context, "Country House Consultancy", "GB");
			SeedDepartmentData(context, "Country User", "GB");
			SeedDepartmentData(context, "Courchevel - CIMALPES - (FRANCE)", "FR");
			SeedDepartmentData(context, "Crans Montana - Altitude Immobilier - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Creative Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Croatia - Sanda Marisuc - (CROATIA)", "HR");
			SeedDepartmentData(context, "CTG-Transaction Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Database Management", "GB");
			SeedDepartmentData(context, "Development & Agricultural Land and Industrial - (IRELAND)", "IE");
			SeedDepartmentData(context, "Development & Agricultural Land and Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, "Development Consultancy - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Development Consultancy & Research - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Development Land - (IRELAND)", "IE");
			SeedDepartmentData(context, "Development Land, Retail, Industrial & Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, "Digital", "GB");
			SeedDepartmentData(context, "Docklands Commercial", "GB");
			SeedDepartmentData(context, "Domestic Hotels", "GB");
			SeedDepartmentData(context, "Dordogne - Classic French Homes - (FRANCE)", "FR");
			SeedDepartmentData(context, "Dublin - (IRELAND)", "IE");
			SeedDepartmentData(context, "Dulwich Sales", "GB");
			SeedDepartmentData(context, "Dulwich Village", "GB");
			SeedDepartmentData(context, "East Anglia Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Edinburgh Commercial", "GB");
			SeedDepartmentData(context, "Edinburgh Residential Development", "GB");
			SeedDepartmentData(context, "Edinburgh Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "EMEA Tenant Representation", "GB");
			SeedDepartmentData(context, "Energy", "GB");
			SeedDepartmentData(context, "Energy", "GB");
			SeedDepartmentData(context, "Enterprise Services, Information Technology - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Esher", "GB");
			SeedDepartmentData(context, "Esher Lettings", "GB");
			SeedDepartmentData(context, "Euro Commercial Valuations User", "GB");
			SeedDepartmentData(context, "Europe", "GB");
			SeedDepartmentData(context, "Europe (new)", "GB");
			SeedDepartmentData(context, "Europe (old)", "GB");
			SeedDepartmentData(context, "European Department [old]", "GB");
			SeedDepartmentData(context, "European Tenant Rep", "GB");
			SeedDepartmentData(context, "European Tenant Representation", "GB");
			SeedDepartmentData(context, "European Valuations", "GB");
			SeedDepartmentData(context, "Events, Hospitality and Charity", "GB");
			SeedDepartmentData(context, "Evian - Laurent Guerineau Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, "Executive Assistant, Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Executive Chairman - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Executive Management & Valuation - (UGANDA)", "UG");
			SeedDepartmentData(context, "Exeter Commercial", "GB");
			SeedDepartmentData(context, "Exeter Residential", "GB");
			SeedDepartmentData(context, "Exeter Residential Development", "GB");
			SeedDepartmentData(context, "Expertises - (FRANCE)", "FR");
			SeedDepartmentData(context, "Facilities Management - (IRELAND)", "IE");
			SeedDepartmentData(context, "Facilities Management - Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Facilities Management  Services (Core Team) - (INDIA)", "IN");
			SeedDepartmentData(context, "Facilities Management - Site - (INDIA)", "IN");
			SeedDepartmentData(context, "Facilities Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Facilities Management-Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, "Facility Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Farms, Estates & Residential Agency - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Finanace - (UGANDA)", "UG");
			SeedDepartmentData(context, "Finance - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Finance - (CHINA)", "CN");
			SeedDepartmentData(context, "Finance - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Finance - (INDIA)", "IN");
			SeedDepartmentData(context, "Finance - (IRELAND)", "IE");
			SeedDepartmentData(context, "Finance - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Finance - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Finance & Property Management - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Finance and Strategy", "GB");
			SeedDepartmentData(context, "Finance, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Financial Controller Town Planning - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Financial Services France [old]", "GB");
			SeedDepartmentData(context, "Florence - (ITALY)", "IT");
			SeedDepartmentData(context, "Florida - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, "FM- Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, "FMS - (INDIA)", "IN");
			SeedDepartmentData(context, "FMS - Site - (INDIA)", "IN");
			SeedDepartmentData(context, "FMS (Core) - (INDIA)", "IN");
			SeedDepartmentData(context, "Franchise - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Frankfurt - (GERMANY)", "DE");
			SeedDepartmentData(context, "Fulham", "GB");
			SeedDepartmentData(context, "Fulham Lettings", "GB");
			SeedDepartmentData(context, "Gascony - Purslow's Gascony - (FRANCE)", "FR");
			SeedDepartmentData(context, "GCS", "GB");
			SeedDepartmentData(context, "GCS - (CHINA)", "CN");
			SeedDepartmentData(context, "GCS - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Geelong Market Square - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "General Management - (RUSSIA)", "RU");
			SeedDepartmentData(context, "General Mangement - (RUSSIA)", "RU");
			SeedDepartmentData(context, "General Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Geneva - Naef Prestige - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Geneva - Partner Real Estate - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Genova, Liguria - IIN Liguria - (ITALY)", "IT");
			SeedDepartmentData(context, "Glasgow", "GB");
			SeedDepartmentData(context, "Glasgow Commercial", "GB");
			SeedDepartmentData(context, "Global Capital Market - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Global Capital Market/ Acquisitions and Disposals - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Global Capital Markets", "GB");
			SeedDepartmentData(context, "Global Capital Markets - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Global Corporate Service - (FRANCE)", "FR");
			SeedDepartmentData(context, "Global Corporate Services", "GB");
			SeedDepartmentData(context, "Global Corporate Services - (FRANCE)", "FR");
			SeedDepartmentData(context, "Global Corporate Services - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Global Corporate Services, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Graduate", "GB");
			SeedDepartmentData(context, "Graduates", "GB");
			SeedDepartmentData(context, "Graduates - (FRANCE)", "FR");
			SeedDepartmentData(context, "Graduates - (SPAIN)", "ES");
			SeedDepartmentData(context, "Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Greek Islands - Ionian International - (GREECE)", "GR");
			SeedDepartmentData(context, "Grimaud - Skillington Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, "Group Chairman", "GB");
			SeedDepartmentData(context, "Group Director GCS, Project Management & Building Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Group Managing Director - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "GSC - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Gstaad - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Guildford", "GB");
			SeedDepartmentData(context, "Guildford Lettings", "GB");
			SeedDepartmentData(context, "Guildford Residential Development", "GB");
			SeedDepartmentData(context, "Hampstead", "GB");
			SeedDepartmentData(context, "Hampstead Lettings", "GB");
			SeedDepartmentData(context, "Hanoi - (VIETNAM)", "VN");
			SeedDepartmentData(context, "Harrogate", "GB");
			SeedDepartmentData(context, "Haslemere", "GB");
			SeedDepartmentData(context, "Head of Capital Markets - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of International Project Marketing - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of Land Advisory Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Head of Landlord Project Services, China - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of Lettings", "GB");
			SeedDepartmentData(context, "Head of Mortgage Valuation (Special Properties) - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Head of Portfolio Optimisation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Head of Research & Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of Tenant Representative, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Head of Valuation & Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Head of Valuation & Professional Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Head Office", "GB");
			SeedDepartmentData(context, "Healthcare", "GB");
			SeedDepartmentData(context, "Henley", "GB");
			SeedDepartmentData(context, "Henley Lettings", "GB");
			SeedDepartmentData(context, "Hereford", "GB");
			SeedDepartmentData(context, "Ho Chi Minh - (VIETNAM)", "VN");
			SeedDepartmentData(context, "Ho Chi Minh - Vietnam - (VIETNAM)", "ES");
			SeedDepartmentData(context, "Holland Park Villas", "GB");
			SeedDepartmentData(context, "Hong Kong", "GB");
			SeedDepartmentData(context, "Horsham", "GB");
			SeedDepartmentData(context, "Hospitality & Leisure - (INDIA)", "IN");
			SeedDepartmentData(context, "Hotels", "GB");
			SeedDepartmentData(context, "Hotels - Birmingham", "GB");
			SeedDepartmentData(context, "Hotels - Exeter", "GB");
			SeedDepartmentData(context, "Hotels - Leeds", "GB");
			SeedDepartmentData(context, "Hotels - West Country", "GB");
			SeedDepartmentData(context, "Hotels - Winchester", "GB");
			SeedDepartmentData(context, "HR - (INDIA)", "IN");
			SeedDepartmentData(context, "HR & Admin - (INDIA)", "IN");
			SeedDepartmentData(context, "HR & Administraction - (RWANDA)", "RW");
			SeedDepartmentData(context, "HR & Administraction - (UGANDA)", "UG");
			SeedDepartmentData(context, "HR and Administration - (RWANDA)", "RW");
			SeedDepartmentData(context, "Human Resources", "GB");
			SeedDepartmentData(context, "Human Resources - (CHINA)", "CN");
			SeedDepartmentData(context, "Human Resources - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Human Resources - (SPAIN)", "ES");
			SeedDepartmentData(context, "Human Resources, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Hungerford", "GB");
			SeedDepartmentData(context, "Hungerford - Estate Office", "GB");
			SeedDepartmentData(context, "Hyde Park", "GB");
			SeedDepartmentData(context, "Hyde Park Lettings", "GB");
			SeedDepartmentData(context, "Hyde Park Sales", "GB");
			SeedDepartmentData(context, "Ibiza - Villa Contact - (SPAIN)", "ES");
			SeedDepartmentData(context, "India", "GB");
			SeedDepartmentData(context, "Industrial - (GERMANY)", "DE");
			SeedDepartmentData(context, "Industrial - (NEW ZEALAND)", "NZ");
			SeedDepartmentData(context, "Industrial - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Industrial - Business Space - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Industrial - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, "Industrial & Asset Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Industrial & Logistics - (SPAIN)", "ES");
			SeedDepartmentData(context, "Industrial & Retail Agency - (CHINA)", "CN");
			SeedDepartmentData(context, "Industrial, Business Space - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Industrial, Parramatta - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Industry department - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Information Centre", "GB");
			SeedDepartmentData(context, "Information Technology", "GB");
			SeedDepartmentData(context, "Information Technology - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Information Technology - (INDIA)", "IN");
			SeedDepartmentData(context, "Information Technology - (SPAIN)", "ES");
			SeedDepartmentData(context, "Information Technology - APAC - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Information Technology, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Information Technology, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Institutional Sales - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Institutional Sales, Capital Markets - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Integrated Development Consultancy - (HONG KONG)", "HK");
			SeedDepartmentData(context, "International Hotels [old]", "GB");
			SeedDepartmentData(context, "International Project Marketing", "GB");
			SeedDepartmentData(context, "International Project Marketing - (CHINA)", "CN");
			SeedDepartmentData(context, "International Project Marketing - (HONG KONG)", "HK");
			SeedDepartmentData(context, "International Residential", "GB");
			SeedDepartmentData(context, "International Residential - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "International Residential Development", "GB");
			SeedDepartmentData(context, "Investment", "GB");
			SeedDepartmentData(context, "Investment - (FRANCE)", "FR");
			SeedDepartmentData(context, "Investment - (GERMANY)", "DE");
			SeedDepartmentData(context, "Investment - (IRELAND)", "IE");
			SeedDepartmentData(context, "Investment - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Investment - (SPAIN)", "ES");
			SeedDepartmentData(context, "Investment and Lettings Management", "GB");
			SeedDepartmentData(context, "Investment Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Investment Lettings and Management", "GB");
			SeedDepartmentData(context, "Investment Lettings and Management", "GB");
			SeedDepartmentData(context, "Investment, Valuation, Residential - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Investment, Valuation, Residential - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Investments", "GB");
			SeedDepartmentData(context, "Investments - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Investments - (FRANCE)", "FR");
			SeedDepartmentData(context, "Investments - (GERMANY)", "DE");
			SeedDepartmentData(context, "Investments - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Investments & Asset Receivership - (IRELAND)", "IE");
			SeedDepartmentData(context, "Investments and Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, "IPM - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Islington", "GB");
			SeedDepartmentData(context, "Islington Lettings", "GB");
			SeedDepartmentData(context, "IT", "GB");
			SeedDepartmentData(context, "IT - (FRANCE)", "FR");
			SeedDepartmentData(context, "IT - (HONG KONG)", "HK");
			SeedDepartmentData(context, "IT - (INDIA)", "IN");
			SeedDepartmentData(context, "IT - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "IT DEPARTMENT - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "IT Dept. - (INDIA)", "IN");
			SeedDepartmentData(context, "IT Projects", "GB");
			SeedDepartmentData(context, "IT Services", "GB");
			SeedDepartmentData(context, "Jumby Bay - Jumby Bay Island - (ANTIGUA AND BARBUDA)", "AG");
			SeedDepartmentData(context, "Junior Negotiator - (POLAND)", "PL");
			SeedDepartmentData(context, "Kensington", "GB");
			SeedDepartmentData(context, "Kensington Lettings", "GB");
			SeedDepartmentData(context, "KF Finance - Home Counties", "GB");
			SeedDepartmentData(context, "KF Investment Management", "GB");
			SeedDepartmentData(context, "KF Valuations - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "KFEM - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Kings Cross Lettings", "GB");
			SeedDepartmentData(context, "Kingston upon Thames", "GB");
			SeedDepartmentData(context, "Knight Frank Asset Management - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Knight Frank Expertises - (FRANCE)", "FR");
			SeedDepartmentData(context, "Knight Frank Finance", "GB");
			SeedDepartmentData(context, "Knight Frank Global Wealth", "GB");
			SeedDepartmentData(context, "Knight Frank Partner Alliance - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Knight Frank Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Knight Frank Valuations Canberra - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Knightsbridge", "GB");
			SeedDepartmentData(context, "Knightsbridge Lettings", "GB");
			SeedDepartmentData(context, "Kowloon Commercial Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Lake Como - (ITALY)", "IT");
			SeedDepartmentData(context, "Land - (INDIA)", "IN");
			SeedDepartmentData(context, "Land Advisory Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Land Agency - (INDIA)", "IN");
			SeedDepartmentData(context, "Landlord Project Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Landlord Representation, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, "LATELIER - (FRANCE)", "FR");
			SeedDepartmentData(context, "Lauder", "GB");
			SeedDepartmentData(context, "Lausanne, Switzerland - Naef Prestige - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Lease Advisory - Landlord / Tenant - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Leasehold Reform", "GB");
			SeedDepartmentData(context, "Leeds", "GB");
			SeedDepartmentData(context, "Leeds Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Leeds Residential Development Vals", "GB");
			SeedDepartmentData(context, "Legal - (SPAIN)", "ES");
			SeedDepartmentData(context, "Legal Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Leisure", "GB");
			SeedDepartmentData(context, "Leisure [old]", "GB");
			SeedDepartmentData(context, "Lettings Operations", "GB");
			SeedDepartmentData(context, "Liverpool Commercial", "GB");
			SeedDepartmentData(context, "Liverpool Residential Development", "GB");
			SeedDepartmentData(context, "Liverpool Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Liverpool Residential Development Vals", "GB");
			SeedDepartmentData(context, "Logistics & Industrial - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Logistics & Industrial Agency", "GB");
			SeedDepartmentData(context, "Logistics and Industrial Agency", "GB");
			SeedDepartmentData(context, "London Residential Development", "GB");
			SeedDepartmentData(context, "London Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "London Residential Head", "GB");
			SeedDepartmentData(context, "Los Angeles - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, "LPS - (CHINA)", "CN");
			SeedDepartmentData(context, "Lucca - Ser.Imm", "BL");
			SeedDepartmentData(context, "Lucca - Ser.Imm - (ITALY)", "IT");
			SeedDepartmentData(context, "Lugano - Emerald Casa - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Lymington", "GB");
			SeedDepartmentData(context, "Madrid - Residential - (SPAIN)", "ES");
			SeedDepartmentData(context, "Mainland Greece - Ploumis Sotiropoulos - (GREECE)", "GR");
			SeedDepartmentData(context, "Malaysia - (MALAYSIA)", "MY");
			SeedDepartmentData(context, "Mallorca - Mallorca Gold - (SPAIN)", "ES");
			SeedDepartmentData(context, "Malta - Belair - (MALTA)", "MT");
			SeedDepartmentData(context, "Management - (BOTSWANA)", "BW");
			SeedDepartmentData(context, "Management - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Management - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, "Management - (TANZANIA)", "TZ");
			SeedDepartmentData(context, "Management Support Division - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Manager- Training - (INDIA)", "IN");
			SeedDepartmentData(context, "Managing Director, Sydney - North Shore - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Manchester City Centre Sales", "GB");
			SeedDepartmentData(context, "Manchester Commercial", "GB");
			SeedDepartmentData(context, "Manchester Residential Development", "GB");
			SeedDepartmentData(context, "Manchester Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Manchester Residential Development Vals", "GB");
			SeedDepartmentData(context, "Mapping", "GB");
			SeedDepartmentData(context, "Marbella - Diana Morales Properties - (SPAIN)", "ES");
			SeedDepartmentData(context, "Marine", "GB");
			SeedDepartmentData(context, "Marketing", "GB");
			SeedDepartmentData(context, "Marketing - (FRANCE)", "FR");
			SeedDepartmentData(context, "Marketing - (IRELAND)", "IE");
			SeedDepartmentData(context, "Marketing - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Marketing & Administration - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Marketing & Communications - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Marketing & Communications - (CHINA)", "CN");
			SeedDepartmentData(context, "Marketing & Communications - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Marketing & Communications - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Marketing & Communications - Agency - (ITALY)", "IT");
			SeedDepartmentData(context, "Marketing & Communications, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Marketing & Internal Projects - (IRELAND)", "IE");
			SeedDepartmentData(context, "Marketing &PR - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Marketing and Communications", "GB");
			SeedDepartmentData(context, "Marketing and Communications - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Marketing and Communications - (IRELAND)", "IE");
			SeedDepartmentData(context, "Marketing and Communications - (SPAIN)", "ES");
			SeedDepartmentData(context, "Marketing NSW - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Marylebone", "GB");
			SeedDepartmentData(context, "Marylebone Lettings", "GB");
			SeedDepartmentData(context, "Mauritius - MJ Property Solutions - (MAURITIUS)", "MU");
			SeedDepartmentData(context, "Mayfair", "GB");
			SeedDepartmentData(context, "Mayfair Lettings", "GB");
			SeedDepartmentData(context, "Megeve - Agence Boan - (FRANCE)", "FR");
			SeedDepartmentData(context, "Meribel - CIMALPES - (FRANCE)", "FR");
			SeedDepartmentData(context, "Michael de Pelet", "GB");
			SeedDepartmentData(context, "Middle East", "GB");
			SeedDepartmentData(context, "Middle Eastern Desk", "GB");
			SeedDepartmentData(context, "Middle Eastern Desk - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Milan - Case di Campagna - (ITALY)", "IT");
			SeedDepartmentData(context, "Milton Keynes Residential Development", "GB");
			SeedDepartmentData(context, "Mixed Use and Residential Asset Management", "GB");
			SeedDepartmentData(context, "Monaco - PVN Real Estate Investments - (MONACO)", "MC");
			SeedDepartmentData(context, "Monpazier - La Porte Property - (FRANCE)", "FR");
			SeedDepartmentData(context, "Mortgage Valuation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Morzine - Morzine Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, "Mougins - (FRANCE)", "FR");
			SeedDepartmentData(context, "MSD - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Munich - (GERMANY)", "DE");
			SeedDepartmentData(context, "Munich - Riedel Immobilien - (GERMANY)", "DE");
			SeedDepartmentData(context, "Mustique - The Mustique Company - (SAINT VINCENT AND THE GRENADINES)", "VC");
			SeedDepartmentData(context, "National Offices", "GB");
			SeedDepartmentData(context, "Neuchatel, Switzerland - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "New Homes", "GB");
			SeedDepartmentData(context, "New Homes - (IRELAND)", "IE");
			SeedDepartmentData(context, "New Lettings Department", "GB");
			SeedDepartmentData(context, "New York - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, "Newcastle Commercial", "GB");
			SeedDepartmentData(context, "Newcastle Promise", "GB");
			SeedDepartmentData(context, "Newcastle Residential Development", "GB");
			SeedDepartmentData(context, "Newcastle Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Newcastle Residential Development Vals", "GB");
			SeedDepartmentData(context, "Newmark Global Corporate Services", "GB");
			SeedDepartmentData(context, "NL Real Estate - (NETHERLANDS)", "NL");
			SeedDepartmentData(context, "Northern Residential Development", "GB");
			SeedDepartmentData(context, "Notting Hill", "GB");
			SeedDepartmentData(context, "Notting Hill Lettings", "GB");
			SeedDepartmentData(context, "Nottingham Residential Development", "GB");
			SeedDepartmentData(context, "Occupier Solutions", "GB");
			SeedDepartmentData(context, "Occupier Solutions - (INDIA)", "IN");
			SeedDepartmentData(context, "Occupier Solutions Group - (INDIA)", "IN");
			SeedDepartmentData(context, "Office - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Office & Industrial - (INDIA)", "IN");
			SeedDepartmentData(context, "Office Administration - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Office Administration - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Office Agency - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Office Agency - (FRANCE)", "FR");
			SeedDepartmentData(context, "Office Agency - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Office and Industrial-IAS - (INDIA)", "IN");
			SeedDepartmentData(context, "Office and Industrial-LRG - (INDIA)", "IN");
			SeedDepartmentData(context, "Office and Industrial-OSG - (INDIA)", "IN");
			SeedDepartmentData(context, "Office Leasing & Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Office Leasing I Asset Management Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Office Leasing, North Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Office Manager - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Offices - (IRELAND)", "IE");
			SeedDepartmentData(context, "Offices - (ROMANIA)", "RO");
			SeedDepartmentData(context, "One Hyde Park", "GB");
			SeedDepartmentData(context, "One Kensington Gardens", "GB");
			SeedDepartmentData(context, "One Tower Bridge Lettings", "GB");
			SeedDepartmentData(context, "Operations - (CHINA)", "CN");
			SeedDepartmentData(context, "Operations - (IRELAND)", "IE");
			SeedDepartmentData(context, "Operations & Risk", "GB");
			SeedDepartmentData(context, "Operations and Risk", "GB");
			SeedDepartmentData(context, "OSG - (INDIA)", "IN");
			SeedDepartmentData(context, "Oslo - Ek - (NORWAY)", "NO");
			SeedDepartmentData(context, "Overseas - (IRELAND)", "IE");
			SeedDepartmentData(context, "Oxford", "GB");
			SeedDepartmentData(context, "Oxford Lettings", "GB");
			SeedDepartmentData(context, "Oxford Residential Development", "GB");
			SeedDepartmentData(context, "Paris - (FRANCE)", "FR");
			SeedDepartmentData(context, "Paris - Belles Demeures de France - (FRANCE)", "FR");
			SeedDepartmentData(context, "Partner - (POLAND)", "PL");
			SeedDepartmentData(context, "Pension Fund", "GB");
			SeedDepartmentData(context, "Planning", "GB");
			SeedDepartmentData(context, "Planning - Regions", "GB");
			SeedDepartmentData(context, "PM- Non Site - (INDIA)", "IN");
			SeedDepartmentData(context, "PM- Site - (INDIA)", "IN");
			SeedDepartmentData(context, "PMC - (INDIA)", "IN");
			SeedDepartmentData(context, "PM-Corporate - (INDIA)", "IN");
			SeedDepartmentData(context, "PMS - (INDIA)", "IN");
			SeedDepartmentData(context, "PMS-Site - (INDIA)", "IN");
			SeedDepartmentData(context, "Portfolio Advisory Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Portfolio Optimisation - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Portfolio Optimisation, Global Corporate Services, Asia Pacific - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Post Room", "GB");
			SeedDepartmentData(context, "Prime Central London", "GB");
			SeedDepartmentData(context, "Prime Central London Developments", "GB");
			SeedDepartmentData(context, "Prime Central London Team", "GB");
			SeedDepartmentData(context, "Prime New Homes", "GB");
			SeedDepartmentData(context, "Print Room", "GB");
			SeedDepartmentData(context, "Professional Consultancy & Valuation - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Professional Services - (IRELAND)", "IE");
			SeedDepartmentData(context, "Professional Services - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Project & Building Consultancy", "GB");
			SeedDepartmentData(context, "Project Management - (CHINA)", "CN");
			SeedDepartmentData(context, "Project Management - (KOREA (SOUTH))", "KR");
			SeedDepartmentData(context, "Project Management and Building Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Project Management Services - (INDIA)", "IN");
			SeedDepartmentData(context, "Project Management Services (Non-Site) - (INDIA)", "IN");
			SeedDepartmentData(context, "Project Management Services (SITE) - (INDIA)", "IN");
			SeedDepartmentData(context, "Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Project Marketing - (MALAYSIA)", "MY");
			SeedDepartmentData(context, "Promise - PAM", "GB");
			SeedDepartmentData(context, "Promise - RAM", "GB");
			SeedDepartmentData(context, "Promise RAM", "GB");
			SeedDepartmentData(context, "Property Accounting Services - Accounts Payable - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Property Accounting Services - National - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Property Accouting Services - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Property Asset Management", "GB");
			SeedDepartmentData(context, "Property Management - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Property Management - (CZECH REPUBLIC)", "CZ");
			SeedDepartmentData(context, "Property Management - (FRANCE)", "FR");
			SeedDepartmentData(context, "Property Management - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Property Management - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Property Management - (IRELAND)", "IE");
			SeedDepartmentData(context, "Property Management - (POLAND)", "PL");
			SeedDepartmentData(context, "Property Management - (TANZANIA)", "TZ");
			SeedDepartmentData(context, "Property Management - (THAILAND)", "TH");
			SeedDepartmentData(context, "Property Management - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Property Management - Commercial (UGANDA) - (UGANDA)", "UG");
			SeedDepartmentData(context, "Property Management - Retail - (UGANDA)", "UG");
			SeedDepartmentData(context, "Property Management & Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, "Property Management & Asset Receivership - (IRELAND)", "IE");
			SeedDepartmentData(context, "Property Management Accounts - (IRELAND)", "IE");
			SeedDepartmentData(context, "Property Management Department - (BELGIUM)", "BE");
			SeedDepartmentData(context, "Property Management Estate - (THAILAND)", "TH");
			SeedDepartmentData(context, "Property management Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, "Property Management Villa - (THAILAND)", "TH");
			SeedDepartmentData(context, "Property Management, Residential - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Property Managemeny Retails - (UGANDA)", "UG");
			SeedDepartmentData(context, "Public Sector", "GB");
			SeedDepartmentData(context, "Queens Park", "GB");
			SeedDepartmentData(context, "Queen's Park", "GB");
			SeedDepartmentData(context, "Queen's Park Lettings", "GB");
			SeedDepartmentData(context, "Queens Park Sales", "GB");
			SeedDepartmentData(context, "Reception - (IRELAND)", "IE");
			SeedDepartmentData(context, "Reception - (ITALY)", "IT");
			SeedDepartmentData(context, "Reception - (SPAIN)", "ES");
			SeedDepartmentData(context, "Reception and Security", "GB");
			SeedDepartmentData(context, "Receptionist - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Regional Investment Team Central", "GB");
			SeedDepartmentData(context, "Registry", "GB");
			SeedDepartmentData(context, "Renewables", "GB");
			SeedDepartmentData(context, "Rent management Retail - (SPAIN)", "ES");
			SeedDepartmentData(context, "Res Vals and Consultancy - Country", "GB");
			SeedDepartmentData(context, "Research", "GB");
			SeedDepartmentData(context, "Research - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Research - (INDIA)", "IN");
			SeedDepartmentData(context, "Research - (POLAND)", "PL");
			SeedDepartmentData(context, "Research - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Research & Consultancy - (CHINA)", "CN");
			SeedDepartmentData(context, "Research & Consultancy, Greater China - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Research & Operations - (FRANCE)", "FR");
			SeedDepartmentData(context, "Research & Valuation - (THAILAND)", "TH");
			SeedDepartmentData(context, "Research and Consultancy - (CAMBODIA)", "KH");
			SeedDepartmentData(context, "Research and Consulting - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Research and Development Consultancy - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Residental Research", "GB");
			SeedDepartmentData(context, "Residential", "GB");
			SeedDepartmentData(context, "Residential - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential - (CHINA)", "CN");
			SeedDepartmentData(context, "Residential - (GERMANY)", "DE");
			SeedDepartmentData(context, "Residential - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Residential - (IRELAND)", "IE");
			SeedDepartmentData(context, "Residential - (ITALY)", "IT");
			SeedDepartmentData(context, "Residential - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Residential - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Residential - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, "Residential - (SPAIN)", "ES");
			SeedDepartmentData(context, "Residential - (THAILAND)", "TH");
			SeedDepartmentData(context, "Residential - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Residential - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Residential - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, "Residential - IPM - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Residential & Project Marketing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential (Leasing) - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Residential (Prime Sales) - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Residential Agency - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Residential Agency - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential Agency - (SPAIN)", "ES");
			SeedDepartmentData(context, "Residential Agency - (TANZANIA)", "TZ");
			SeedDepartmentData(context, "Residential Asset Management", "GB");
			SeedDepartmentData(context, "Residential Business Development Unit", "GB");
			SeedDepartmentData(context, "Residential Capital Markets", "GB");
			SeedDepartmentData(context, "Residential Channel - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential City - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Residential Corporate Services", "GB");
			SeedDepartmentData(context, "Residential Country Business ", "GB");
			SeedDepartmentData(context, "Residential Country Business - Head", "GB");
			SeedDepartmentData(context, "Residential Development", "GB");
			SeedDepartmentData(context, "Residential Development Capital Markets", "GB");
			SeedDepartmentData(context, "Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Residential Developments - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential Division - Head", "GB");
			SeedDepartmentData(context, "Residential Division Head", "GB");
			SeedDepartmentData(context, "Residential Graduate", "GB");
			SeedDepartmentData(context, "Residential Graduates", "GB");
			SeedDepartmentData(context, "Residential International - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Residential Investment and International Project Marketing", "GB");
			SeedDepartmentData(context, "Residential IPM - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential Lettings Accounts", "GB");
			SeedDepartmentData(context, "Residential Lettings Head", "GB");
			SeedDepartmentData(context, "Residential Lettings Investments", "GB");
			SeedDepartmentData(context, "Residential Lettings IPM", "GB");
			SeedDepartmentData(context, "Residential Lettings Management", "GB");
			SeedDepartmentData(context, "Residential London Head", "GB");
			SeedDepartmentData(context, "Residential Milan Office - (ITALY)", "IT");
			SeedDepartmentData(context, "Residential Prime Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, "Residential Project Marketing - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential Project Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, "Residential Property Managemenr - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential Property Management Wharf One & Two - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential Research", "GB");
			SeedDepartmentData(context, "Residential Sale", "GB");
			SeedDepartmentData(context, "Residential Sale - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Residential Sales - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Residential Sales - (INDIA)", "IN");
			SeedDepartmentData(context, "Residential sales - (KENYA)", "KE");
			SeedDepartmentData(context, "Residential Sales - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Residential Valuation and Consultancy- Country", "GB");
			SeedDepartmentData(context, "Residential Valuation and Consultancy- London", "GB");
			SeedDepartmentData(context, "Residential, Asia Pacific - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Resodential - (RUSSIA)", "RU");
			SeedDepartmentData(context, "resres - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Rest of US - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, "Restructuring and Recoveries", "GB");
			SeedDepartmentData(context, "Restructuring and Recovery", "GB");
			SeedDepartmentData(context, "Retail", "GB");
			SeedDepartmentData(context, "Retail - (FRANCE)", "FR");
			SeedDepartmentData(context, "Retail - (INDIA)", "IN");
			SeedDepartmentData(context, "Retail - (IRELAND)", "IE");
			SeedDepartmentData(context, "Retail - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Retail - (UGANDA)", "UG");
			SeedDepartmentData(context, "Retail Agency", "GB");
			SeedDepartmentData(context, "Retail Agency - (INDIA)", "IN");
			SeedDepartmentData(context, "Retail Agency - (POLAND)", "PL");
			SeedDepartmentData(context, "Retail Asset Management - (POLAND)", "PL");
			SeedDepartmentData(context, "Retail Services - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Retail Services and Asset Management - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Retail/Property Management - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Richmond", "GB");
			SeedDepartmentData(context, "Richmond Lettings", "GB");
			SeedDepartmentData(context, "Riverside", "GB");
			SeedDepartmentData(context, "Riverside Lettings", "GB");
			SeedDepartmentData(context, "Riverside Sales", "GB");
			SeedDepartmentData(context, "RL - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Rome - Immobili di Prestigio - (ITALY)", "IT");
			SeedDepartmentData(context, "Royal Wharf", "GB");
			SeedDepartmentData(context, "RS Prime Sales - (THAILAND)", "TH");
			SeedDepartmentData(context, "Rural Consultancy", "GB");
			SeedDepartmentData(context, "Rural Consultancy - Bishops Stortford", "GB");
			SeedDepartmentData(context, "Rural Consultancy - Cotswolds", "GB");
			SeedDepartmentData(context, "Rural Consultancy Bishops Stortford", "GB");
			SeedDepartmentData(context, "Rural Consultancy Bristol", "GB");
			SeedDepartmentData(context, "Rural Consultancy Cotswolds", "GB");
			SeedDepartmentData(context, "Rural Consultancy Solent", "GB");
			SeedDepartmentData(context, "Russia Desk", "GB");
			SeedDepartmentData(context, "Rutley Capital Partners", "GB");
			SeedDepartmentData(context, "Sales - (ITALY)", "IT");
			SeedDepartmentData(context, "Sales & Leasing - (MALAYSIA)", "MY");
			SeedDepartmentData(context, "Sales & Leasing, South Sydney - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Sanremo, Liguria - Liguria Homes", "BL");
			SeedDepartmentData(context, "Sanremo, Liguria - Liguria Homes - (ITALY)", "IT");
			SeedDepartmentData(context, "SAP Project Team / HR", "GB");
			SeedDepartmentData(context, "Sardinia - Immobiliare Brunati - (ITALY)", "IT");
			SeedDepartmentData(context, "Sarteano - Tuscany Inside Out - (ITALY)", "IT");
			SeedDepartmentData(context, "Scotland Res Dev Vals [old]", "GB");
			SeedDepartmentData(context, "Scotland Residential", "GB");
			SeedDepartmentData(context, "Scotland Residential - Lauder", "GB");
			SeedDepartmentData(context, "Scotland Residential Development", "GB");
			SeedDepartmentData(context, "Scotland Residential Development [old]", "GB");
			SeedDepartmentData(context, "Scotland Residential Development Consultancy", "GB");
			SeedDepartmentData(context, "Secretariat and Pensions", "GB");
			SeedDepartmentData(context, "Senior Executive Team - (SPAIN)", "ES");
			SeedDepartmentData(context, "Senior Partner", "GB");
			SeedDepartmentData(context, "Sevenoaks", "GB");
			SeedDepartmentData(context, "Sevenoaks Residential Development", "GB");
			SeedDepartmentData(context, "Shanghai", "GB");
			SeedDepartmentData(context, "Sheffield Residential Development", "GB");
			SeedDepartmentData(context, "Sherborne", "GB");
			SeedDepartmentData(context, "Sicily - thinkSicily - (ITALY)", "IT");
			SeedDepartmentData(context, "Solent", "GB");
			SeedDepartmentData(context, "Solent Residential Development", "GB");
			SeedDepartmentData(context, "Sotogrande - Holmes Sotogrande - (SPAIN)", "ES");
			SeedDepartmentData(context, "South Africa - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, "South Asia Desk", "GB");
			SeedDepartmentData(context, "South East Offices", "GB");
			SeedDepartmentData(context, "South Kensingtion Lettings", "GB");
			SeedDepartmentData(context, "South Kensington", "GB");
			SeedDepartmentData(context, "South Kensington Lettings", "GB");
			SeedDepartmentData(context, "South Kensington Sales", "GB");
			SeedDepartmentData(context, "South Sydney Agency - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "South Sydney Sales and Leasing - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "South Sydney, Industrial - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "South West Residential Development", "GB");
			SeedDepartmentData(context, "Southampton Residential Development", "GB");
			SeedDepartmentData(context, "St Barts - Sibarth Real Estate", "BL");
			SeedDepartmentData(context, "St Barts - Sibarth Real Estate - (ST BARTS)", "BL");
			SeedDepartmentData(context, "St Johns Wood", "GB");
			SeedDepartmentData(context, "St Johns Wood Lettings", "GB");
			SeedDepartmentData(context, "St Remy de Provence - Janssens Immobilier - (FRANCE)", "FR");
			SeedDepartmentData(context, "Stow On The Wold", "GB");
			SeedDepartmentData(context, "Strategic Cons & Public Sector", "GB");
			SeedDepartmentData(context, "Strategic Consulting - (RUSSIA)", "RU");
			SeedDepartmentData(context, "Strategic Occupier Transactions", "GB");
			SeedDepartmentData(context, "Stratford", "GB");
			SeedDepartmentData(context, "Stratford Lettings", "GB");
			SeedDepartmentData(context, "Stratford New Homes", "GB");
			SeedDepartmentData(context, "Stratford Residential Development", "GB");
			SeedDepartmentData(context, "Stratford Residential Development New Homes", "GB");
			SeedDepartmentData(context, "Student Program - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Student Program, NSW - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Student Property", "GB");
			SeedDepartmentData(context, "Student Property Residential Development", "GB");
			SeedDepartmentData(context, "Support - (HONG KONG)", "HK");
			SeedDepartmentData(context, "Support - (INDONESIA)", "ID");
			SeedDepartmentData(context, "Sustainability & Energy", "GB");
			SeedDepartmentData(context, "Sustainability & Energy Consultancy", "GB");
			SeedDepartmentData(context, "Sutton Coldfield", "GB");
			SeedDepartmentData(context, "Sydney Commercial ( Asian Markets) - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Taiwan - (CHINA)", "CN");
			SeedDepartmentData(context, "Tax Department", "GB");
			SeedDepartmentData(context, "Telephone Room", "GB");
			SeedDepartmentData(context, "Tenancy Management", "GB");
			SeedDepartmentData(context, "Tenant Representation, Commercial Services - (CHINA)", "CN");
			SeedDepartmentData(context, "Test Department", "GB");
			SeedDepartmentData(context, "Thames Gateway", "GB");
			SeedDepartmentData(context, "Thames Gateway", "GB");
			SeedDepartmentData(context, "The Buying Solution - Country", "GB");
			SeedDepartmentData(context, "The Buying Solution - London", "GB");
			SeedDepartmentData(context, "The City", "GB");
			SeedDepartmentData(context, "Third-Party USA - Douglas Elliman - (UNITED STATES OF AMERICA)", "US");
			SeedDepartmentData(context, "Tower Bridge", "GB");
			SeedDepartmentData(context, "Tower Bridge Lettings", "GB");
			SeedDepartmentData(context, "Tower Bridge Sales", "GB");
			SeedDepartmentData(context, "Tunbridge Wells", "GB");
			SeedDepartmentData(context, "Umbria - Abode - (ITALY)", "IT");
			SeedDepartmentData(context, "US Alliance Development", "GB");
			SeedDepartmentData(context, "Val d'Isere - Agence Val d'Isere - (FRANCE)", "FR");
			SeedDepartmentData(context, "Valbonne - (FRANCE)", "FR");
			SeedDepartmentData(context, "Valuation - (BOTSWANA)", "BW");
			SeedDepartmentData(context, "Valuation - (CHINA)", "CN");
			SeedDepartmentData(context, "Valuation - (FRANCE)", "FR");
			SeedDepartmentData(context, "Valuation - (ITALY)", "IT");
			SeedDepartmentData(context, "Valuation - (SINGAPORE)", "SG");
			SeedDepartmentData(context, "Valuation - (UGANDA)", "UG");
			SeedDepartmentData(context, "Valuation - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, "Valuation & Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Valuation & Consultancy - (THAILAND)", "TH");
			SeedDepartmentData(context, "Valuation & Research - (KENYA)", "KE");
			SeedDepartmentData(context, "Valuation and Consultancy - (THAILAND)", "TH");
			SeedDepartmentData(context, "Valuation Consultancy - (FRANCE)", "FR");
			SeedDepartmentData(context, "Valuations - (FRANCE)", "FR");
			SeedDepartmentData(context, "Valuations - (GERMANY)", "DE");
			SeedDepartmentData(context, "Valuations - (IRELAND)", "IE");
			SeedDepartmentData(context, "Valuations - (ITALY)", "IT");
			SeedDepartmentData(context, "Valuations - (MALAYSIA)", "MY");
			SeedDepartmentData(context, "Valuations - (POLAND)", "PL");
			SeedDepartmentData(context, "Valuations - (PORTUGAL)", "PT");
			SeedDepartmentData(context, "Valuations - (SOUTH AFRICA)", "ZA");
			SeedDepartmentData(context, "Valuations - (SPAIN)", "ES");
			SeedDepartmentData(context, "Valuations - (TANZANIA)", "TZ");
			SeedDepartmentData(context, "Valuations - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Valuations - (ZAMBIA)", "ZM");
			SeedDepartmentData(context, "Valuations - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, "Valuations - Germany - (GERMANY)", "DE");
			SeedDepartmentData(context, "Valuations & Consultancy - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Valuations & Research - (KENYA)", "KE");
			SeedDepartmentData(context, "Valuations and Professional Services - (UNITED ARAB EMIRATES)", "AE");
			SeedDepartmentData(context, "Valuations QLD - (AUSTRALIA)", "AU");
			SeedDepartmentData(context, "Valuations, Agency, Research & Consultancy, Investment - (CAMBODIA)", "KH");
			SeedDepartmentData(context, "Valuations/Property Management - (POLAND)", "PL");
			SeedDepartmentData(context, "Valuations/Sales - (ZIMBABWE)", "ZW");
			SeedDepartmentData(context, "Valuer - (UGANDA)", "UG");
			SeedDepartmentData(context, "Vancouver - Dexter Realty - (CANADA)", "CA");
			SeedDepartmentData(context, "Venice - Venice Real Estate - (ITALY)", "IT");
			SeedDepartmentData(context, "Verbier - Guinnard Immobilier SA - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Vienna - OTTO Immobilien - (AUSTRIA)", "AT");
			SeedDepartmentData(context, "Villars - Regie Turrian SA - (SWITZERLAND)", "CH");
			SeedDepartmentData(context, "Virginia Water", "GB");
			SeedDepartmentData(context, "Vision", "GB");
			SeedDepartmentData(context, "Wandsworth", "GB");
			SeedDepartmentData(context, "Wandsworth Lettings", "GB");
			SeedDepartmentData(context, "Wapping", "GB");
			SeedDepartmentData(context, "Wapping Lettings", "GB");
			SeedDepartmentData(context, "Waterfront", "GB");
			SeedDepartmentData(context, "Web site", "GB");
			SeedDepartmentData(context, "West Country Healthcare", "GB");
			SeedDepartmentData(context, "West Country Hotels", "GB");
			SeedDepartmentData(context, "West End Agency", "GB");
			SeedDepartmentData(context, "West End Capital Markets", "GB");
			SeedDepartmentData(context, "West End Development", "GB");
			SeedDepartmentData(context, "West End Investment", "GB");
			SeedDepartmentData(context, "West End Investments", "GB");
			SeedDepartmentData(context, "West End Office", "GB");
			SeedDepartmentData(context, "West End Offices", "GB");
			SeedDepartmentData(context, "Western Algarve - Sadler's Properties - (PORTUGAL)", "PT");
			SeedDepartmentData(context, "Western Residential Development", "GB");
			SeedDepartmentData(context, "Westminster City Council", "GB");
			SeedDepartmentData(context, "Westminster City Council Team", "GB");
			SeedDepartmentData(context, "Wimbledon", "GB");
			SeedDepartmentData(context, "Wimbledon Lettings", "GB");
			SeedDepartmentData(context, "Winchester", "GB");
			SeedDepartmentData(context, "Worcester", "GB");
			SeedDepartmentData(context, "Worcester Residential Development", "GB");
			SeedDepartmentData(context, "Workplace Consultancy", "GB");
			SeedDepartmentData(context, "Yorkshire Commercial", "GB");
			SeedDepartmentData(context, "Yorkshire Residential Development", "GB");
			SeedDepartmentData(context, "Zurich - Ginesta Immobilien - (SWITZERLAND)", "CH");
		}

		private static void SeedDepartmentData(KnightFrankContext context, string name, string countryCode)
		{
			var department = new Department
			{
				Name = name,
				CountryId = GetCountryIdByCode(context, countryCode)
			};

			context.Department.AddOrUpdate(x => x.Name, department);
			context.SaveChanges();
		}

		private static Guid GetCountryIdByCode(KnightFrankContext context, string countryCode)
		{
			Country country = context.Country.FirstOrDefault(c => c.IsoCode == countryCode);

			return country?.Id ?? default(Guid);
		}
	}
}