module Antares.Common.Models.Dto {
    export enum EnumTypeCode {
        EntityType = <any>'entityType',
        OwnershipType = <any>'ownershipType',
        ActivityStatus = <any>'activityStatus',
        ActivityType = <any>'activityType',
        Division = <any>'division',
        ActivityDocumentType = <any>'activityDocumentType',
        ActivityDepartmentType = <any>'activityDepartmentType',
        PropertyDocumentType = <any>'propertyDocumentType',
        RequirementDocumentType = <any>'requirementDocumentType',
        RequirementType = <any>'requirementType',
        OfferStatus = <any>'offerStatus',
        MortgageStatus = <any>'mortgageStatus',
        MortgageSurveyStatus = <any>'mortgageSurveyStatus',
        ClientCareStatus = <any>'clientCareStatus',
        AdditionalSurveyStatus = <any>'additionalSurveyStatus',
        SearchStatus = <any>'searchStatus',
        Enquiries = <any>'enquiries',
        SalutationFormat = <any>'salutationFormat',
        MailingSalutation = <any>'mailingSalutation',
        EventSalutation = <any>'eventSalutation',
        ActivitySource = <any>'activitySource',
        ActivitySellingReason = <any>'activitySellingReason',
        DisposalType = <any>'disposalType',
        Decoration = <any>'decoration',
        ChainMortgageStatus = <any>'chainMortgageStatus',
        ChainMortgageSurveyStatus = <any>'chainMortgageSurveyStatus',
        ChainSearchStatus = <any>'chainSearchStatus',
        ChainEnquiries = <any>'chainEnquiries',
        ChainContractAgreedStatus = <any>'chainContractAgreedStatus'
    }
}