:r .\SQL\Locale.sql
:r .\SQL\Country.sql
:r .\SQL\CountryLocalised.sql
:r .\SQL\Department.sql
:r .\SQL\Business.sql
:r .\SQL\EnumType.sql
:r .\SQL\EnumTypeItem.sql
:r .\SQL\EnumLocalised.sql
:r .\SQL\PropertyType.sql
:r .\SQL\PropertyTypeDefinition.sql
:r .\SQL\PropertyTypeLocalised.sql
:r .\SQL\Attribute.sql
:r .\SQL\PropertyAttributeForm.sql
:r .\SQL\PropertyAttributeFormDefinition.sql
:r .\SQL\AddressField.sql
--:r .\SQL\AddressForm.sql
:r .\SQL\AddressFieldLabel.sql
:r .\SQL\AddressFieldDefinition.sql
--:r .\SQL\AddressFormEntityType.sql
:r .\SQL\Role.sql
:r .\SQL\User.sql
:r .\SQL\RoleUser.sql
:r .\SQL\Characteristic.sql
:r .\SQL\CharacteristicGroup.sql
:r .\SQL\CharacteristicLocalised.sql
:r .\SQL\CharacteristicGroupLocalised.sql
:r .\SQL\CharacteristicGroupUsageItems.sql
:r .\SQL\Contact.sql
:r .\SQL\ActivityType.sql
:r .\SQL\ActivityTypeDefinition.sql
:r .\SQL\ActivityTypeLocalised.sql
:r .\SQL\RequirementType.sql
:r .\SQL\RequirementTypeActivityTypeDefinition.sql
:r .\SQL\RequirementTypeLocalised.sql
:r .\SQL\OfferType.sql
:r .\SQL\OfferTypeLocalised.sql
:r .\SQL\TenancyType.sql

:r .\Views\ElasticSearchContact.sql
:r .\Views\ElasticSearchProperty.sql