:r .\SQL\Locale.sql
:r .\SQL\Country.sql
:r .\SQL\CountryLocalised.sql
:r .\SQL\Department.sql
:r .\SQL\Business.sql
:r .\SQL\Role.sql
:r .\SQL\EnumType.sql
:r .\SQL\EnumTypeItem.sql
:r .\SQL\EnumLocalised.sql
:r .\SQL\PropertyType.sql
:r .\SQL\PropertyTypeDefinition.sql
:r .\SQL\PropertyTypeLocalised.sql
:r .\SQL\Attribute.sql
--:r .\SQL\PropertyAttributeForm.sql
--:r .\SQL\PropertyAttributeFormDefinition.sql
--:r .\SQL\AddressField.sql
--:r .\SQL\AddressForm.sql
--:r .\SQL\AddressFieldLabel.sql
--:r .\SQL\AddressFieldDefinition.sql
--:r .\SQL\AddressFormEntityType.sql

--:r .\SQL\Contact.sql
