// <copyright file="CompanyCategory.tt">
// </copyright>
// ReSharper disable InconsistentNaming
namespace KnightFrank.Antares.Domain.Common.Enums
{
	public enum CompanyCategory {
		Accountants,
    	AgriculturalAndFarming,
    	Apparel,
    	ArchitectsDesign,
    	AssetManagement,
    	Banks,
    	BooksStationery,
    	BuildingAndConstruction,
    	BusinessServices,
    	BuyingAgent,
    	CareHome,
    	CharitiesAndChurches,
    	Chemist,
    	DeptVariety,
    	EateriesBars,
    	Education,
    	ElectricalTelephones,
    	EmploymentAgency,
    	EquestrianStud,
    	FamilyOffice,
    	Finance,
    	FoodDrinkRetailers,
    	GeneralServices,
    	Hotel,
    	Industrial,
    	Insurance,
    	InvestorsFundManagers,
    	Legal,
    	LocalAuthorityGovernment,
    	MediaAndPublishing,
    	MedicalHealthcare,
    	MultiFamilyOffice,
    	OilAndGas,
    	Other,
    	PropertyCompany ,
    	PropertyConsultantsSurveyors,
    	RenewablesSustainability,
    	Retailers,
    	Supermarkets,
    	TelecommunicationsTechnology,
    	TourismLeisure,
    	Transport,
    	TravelAgents,
    	Utilities,
    	Wholesale,
    }
}
