//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnightFrank.Antares.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnightFrank.Antares.Domain.Properties.BusinessErrorMessages", typeof(BusinessErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity negotiator call date cannot be set in the past..
        /// </summary>
        internal static string Activity_Negotiator_CallDate_InPast {
            get {
                return ResourceManager.GetString("Activity_Negotiator_CallDate_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more negotiators are duplicated..
        /// </summary>
        internal static string Activity_Negotiators_Not_Unique {
            get {
                return ResourceManager.GetString("Activity_Negotiators_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0}(s) with given ids does not exist in the database..
        /// </summary>
        internal static string Entity_List_Item_Not_Exists {
            get {
                return ResourceManager.GetString("Entity_List_Item_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with given id &apos;{1}&apos; does not exist in the database..
        /// </summary>
        internal static string Entity_Not_Exists {
            get {
                return ResourceManager.GetString("Entity_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type {0} with given item id &apos;{1}&apos; does not exist in the database..
        /// </summary>
        internal static string EnumType_Item_Not_Exists {
            get {
                return ResourceManager.GetString("EnumType_Item_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent address country with address form definition..
        /// </summary>
        internal static string Inconsistent_Address_Country_Id {
            get {
                return ResourceManager.GetString("Inconsistent_Address_Country_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration is inconsistent..
        /// </summary>
        internal static string Inconsistent_Dynamic_Configuration {
            get {
                return ResourceManager.GetString("Inconsistent_Dynamic_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more vendors are not exist..
        /// </summary>
        internal static string Missing_Activity_Vendors_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_Vendors_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contacts are not exist..
        /// </summary>
        internal static string Missing_Company_Contacts_Id {
            get {
                return ResourceManager.GetString("Missing_Company_Contacts_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attendees are not on the applicant list..
        /// </summary>
        internal static string Missing_Requirement_Applicants_Id {
            get {
                return ResourceManager.GetString("Missing_Requirement_Applicants_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attendees are not on the applicant list..
        /// </summary>
        internal static string Missing_Requirement_Attendees_Id {
            get {
                return ResourceManager.GetString("Missing_Requirement_Attendees_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only commercial property should have area breakdown..
        /// </summary>
        internal static string Only_Commercial_Property_Should_Have_AreaBreakdown {
            get {
                return ResourceManager.GetString("Only_Commercial_Property_Should_Have_AreaBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ownership dates overlap..
        /// </summary>
        internal static string Ownership_Dates_Overlap {
            get {
                return ResourceManager.GetString("Ownership_Dates_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value format is inappropriate..
        /// </summary>
        internal static string Property_Format_Is_Invalid {
            get {
                return ResourceManager.GetString("Property_Format_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value should be empty..
        /// </summary>
        internal static string Property_Should_Be_Empty {
            get {
                return ResourceManager.GetString("Property_Should_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value is required..
        /// </summary>
        internal static string Property_Should_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Property_Should_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area breakdown  is assigned to other property.
        /// </summary>
        internal static string PropertyAreaBreakdown_Is_Assigned_To_Other_Property {
            get {
                return ResourceManager.GetString("PropertyAreaBreakdown_Is_Assigned_To_Other_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified order is out of available range..
        /// </summary>
        internal static string PropertyAreaBreakdown_OrderOutOfRange {
            get {
                return ResourceManager.GetString("PropertyAreaBreakdown_OrderOutOfRange", resourceCulture);
            }
        }
    }
}
