//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnightFrank.Antares.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusinessErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnightFrank.Antares.Domain.Properties.BusinessErrorMessages", typeof(BusinessErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attendees are duplicated..
        /// </summary>
        internal static string Activity_AppraisalMeetingAttendees_Not_Unique {
            get {
                return ResourceManager.GetString("Activity_AppraisalMeetingAttendees_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More then one chain transaction is marked as last chain transaction..
        /// </summary>
        internal static string Activity_ChainTransactions_IsEndCountMoreThenOne {
            get {
                return ResourceManager.GetString("Activity_ChainTransactions_IsEndCountMoreThenOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contacts are duplicated..
        /// </summary>
        internal static string Activity_Contacts_Not_Unique {
            get {
                return ResourceManager.GetString("Activity_Contacts_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more departments are duplicated..
        /// </summary>
        internal static string Activity_Departments_Not_Unique {
            get {
                return ResourceManager.GetString("Activity_Departments_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity lead negotiator is required..
        /// </summary>
        internal static string Activity_LeadNegotiator_Is_Required {
            get {
                return ResourceManager.GetString("Activity_LeadNegotiator_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity negotiator call date cannot be set in the past..
        /// </summary>
        internal static string Activity_Negotiator_CallDate_InPast {
            get {
                return ResourceManager.GetString("Activity_Negotiator_CallDate_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more negotiators are duplicated..
        /// </summary>
        internal static string Activity_Negotiators_Not_Unique {
            get {
                return ResourceManager.GetString("Activity_Negotiators_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity should have exactly one managing department..
        /// </summary>
        internal static string Activity_Should_Have_Exactly_One_Managing_Department {
            get {
                return ResourceManager.GetString("Activity_Should_Have_Exactly_One_Managing_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent of added transaction chain must be last transaction chain..
        /// </summary>
        internal static string ActivityChainTransactionAdd_InvalidParentId {
            get {
                return ResourceManager.GetString("ActivityChainTransactionAdd_InvalidParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add more than one transaction chain..
        /// </summary>
        internal static string ActivityChainTransactionAdd_MoreThanOne {
            get {
                return ResourceManager.GetString("ActivityChainTransactionAdd_MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add and remove chain and the same time..
        /// </summary>
        internal static string ActivityChainTransactionAddRemove_AtSameTime {
            get {
                return ResourceManager.GetString("ActivityChainTransactionAddRemove_AtSameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd party Agent has been selected, cannot use Knight Frank Agent..
        /// </summary>
        internal static string ActivityChainTransactionAgentContact_InvalidValue {
            get {
                return ResourceManager.GetString("ActivityChainTransactionAgentContact_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight Frank Agent has been selected, cannot use 3rd party Agent..
        /// </summary>
        internal static string ActivityChainTransactionAgentUser_InvalidValue {
            get {
                return ResourceManager.GetString("ActivityChainTransactionAgentUser_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only last chain transaction can be marked as end transaction..
        /// </summary>
        internal static string ActivityChainTransactionEnd_InvalidValue {
            get {
                return ResourceManager.GetString("ActivityChainTransactionEnd_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed transaction chain must be last transaction chain..
        /// </summary>
        internal static string ActivityChainTransactionRemove_InvalidId {
            get {
                return ResourceManager.GetString("ActivityChainTransactionRemove_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot remove more than one transaction chain..
        /// </summary>
        internal static string ActivityChainTransactionRemove_MoreThanOne {
            get {
                return ResourceManager.GetString("ActivityChainTransactionRemove_MoreThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of ActivityDepartment is invalid..
        /// </summary>
        internal static string ActivityDepartment_Invalid_Value {
            get {
                return ResourceManager.GetString("ActivityDepartment_Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call date is required..
        /// </summary>
        internal static string ActivityUser_CallDate_Is_Required {
            get {
                return ResourceManager.GetString("ActivityUser_CallDate_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negotiator is assigned to other activity..
        /// </summary>
        internal static string ActivityUser_Is_Assigned_To_Other_Activity {
            get {
                return ResourceManager.GetString("ActivityUser_Is_Assigned_To_Other_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor value is longer than 128 characters..
        /// </summary>
        internal static string ActivityVendor_ValueToLong {
            get {
                return ResourceManager.GetString("ActivityVendor_ValueToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Survey Date must be greater than or equal to {0}..
        /// </summary>
        internal static string AdditionalSurveyDateGreaterOrEqualToCreateDate {
            get {
                return ResourceManager.GetString("AdditionalSurveyDateGreaterOrEqualToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date must be greater than or equal to {0}..
        /// </summary>
        internal static string CompletionDateGreaterOrEqualToCreateDate {
            get {
                return ResourceManager.GetString("CompletionDateGreaterOrEqualToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0}(s) with given ids does not exist in the database..
        /// </summary>
        internal static string Entity_List_Item_Not_Exists {
            get {
                return ResourceManager.GetString("Entity_List_Item_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with given id &apos;{1}&apos; does not exist in the database..
        /// </summary>
        internal static string Entity_Not_Exists {
            get {
                return ResourceManager.GetString("Entity_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value of the field {0} not passed.
        /// </summary>
        internal static string Enum_Value_Not_Passed {
            get {
                return ResourceManager.GetString("Enum_Value_Not_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum type {0} with given item id &apos;{1}&apos; does not exist in the database..
        /// </summary>
        internal static string EnumType_Item_Not_Exists {
            get {
                return ResourceManager.GetString("EnumType_Item_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Date must be greater than or equal to {0}..
        /// </summary>
        internal static string ExchangeDateGreaterOrEqualToCreateDate {
            get {
                return ResourceManager.GetString("ExchangeDateGreaterOrEqualToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconsistent address country with address form definition..
        /// </summary>
        internal static string Inconsistent_Address_Country_Id {
            get {
                return ResourceManager.GetString("Inconsistent_Address_Country_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration is inconsistent..
        /// </summary>
        internal static string Inconsistent_Dynamic_Configuration {
            get {
                return ResourceManager.GetString("Inconsistent_Dynamic_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more appraisal meeting attendees do not exist..
        /// </summary>
        internal static string Missing_Activity_Attendees_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_Attendees_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more chain transactions do not exist..
        /// </summary>
        internal static string Missing_Activity_ChainTransaction_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_ChainTransaction_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contacts do not exist..
        /// </summary>
        internal static string Missing_Activity_Contacts_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_Contacts_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more departments do not exist..
        /// </summary>
        internal static string Missing_Activity_Departments_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_Departments_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more negotiators do not exist..
        /// </summary>
        internal static string Missing_Activity_Negotiators_Id {
            get {
                return ResourceManager.GetString("Missing_Activity_Negotiators_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contacts do not exist..
        /// </summary>
        internal static string Missing_Company_Contacts_Id {
            get {
                return ResourceManager.GetString("Missing_Company_Contacts_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attendees are not on the applicant list..
        /// </summary>
        internal static string Missing_Requirement_Applicants_Id {
            get {
                return ResourceManager.GetString("Missing_Requirement_Applicants_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more attendees are not on the applicant list..
        /// </summary>
        internal static string Missing_Requirement_Attendees_Id {
            get {
                return ResourceManager.GetString("Missing_Requirement_Attendees_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contacts do not exist..
        /// </summary>
        internal static string Missing_Tenancy_Contacts_Id {
            get {
                return ResourceManager.GetString("Missing_Tenancy_Contacts_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Survey Date must be greater than or equal to {0}..
        /// </summary>
        internal static string MortgageSurveyDateGreaterOrEqualToCreateDate {
            get {
                return ResourceManager.GetString("MortgageSurveyDateGreaterOrEqualToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more negotiators are duplicated..
        /// </summary>
        internal static string Negotiators_Not_Unique {
            get {
                return ResourceManager.GetString("Negotiators_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Date must be less than or equal to {0}..
        /// </summary>
        internal static string OfferDateLessOrEqualToCreateDate {
            get {
                return ResourceManager.GetString("OfferDateLessOrEqualToCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only commercial property should have area breakdown..
        /// </summary>
        internal static string Only_Commercial_Property_Should_Have_AreaBreakdown {
            get {
                return ResourceManager.GetString("Only_Commercial_Property_Should_Have_AreaBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ownership dates overlap..
        /// </summary>
        internal static string Ownership_Dates_Overlap {
            get {
                return ResourceManager.GetString("Ownership_Dates_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value format is inappropriate..
        /// </summary>
        internal static string Property_Format_Is_Invalid {
            get {
                return ResourceManager.GetString("Property_Format_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value should be empty..
        /// </summary>
        internal static string Property_Should_Be_Empty {
            get {
                return ResourceManager.GetString("Property_Should_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property value is required..
        /// </summary>
        internal static string Property_Should_Not_Be_Empty {
            get {
                return ResourceManager.GetString("Property_Should_Not_Be_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area breakdown  is assigned to other property.
        /// </summary>
        internal static string PropertyAreaBreakdown_Is_Assigned_To_Other_Property {
            get {
                return ResourceManager.GetString("PropertyAreaBreakdown_Is_Assigned_To_Other_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified order is out of available range..
        /// </summary>
        internal static string PropertyAreaBreakdown_OrderOutOfRange {
            get {
                return ResourceManager.GetString("PropertyAreaBreakdown_OrderOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more contact are duplicated..
        /// </summary>
        internal static string Tenancy_Contacts_Not_Unique {
            get {
                return ResourceManager.GetString("Tenancy_Contacts_Not_Unique", resourceCulture);
            }
        }
    }
}
