// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace KnightFrank.Antares.Api.IntegrationTests.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ResidentialSalesRequirementsFeature : Xunit.IClassFixture<ResidentialSalesRequirementsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ResidentialSalesRequirement.feature"
#line hidden
        
        public ResidentialSalesRequirementsFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Residential sales requirements", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(ResidentialSalesRequirementsFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Residential sales requirements")]
        [Xunit.TraitAttribute("Description", "Save requirement to DB with contact and all detailed fields fulfilled")]
        public virtual void SaveRequirementToDBWithContactAndAllDetailedFieldsFulfilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save requirement to DB with contact and all detailed fields fulfilled", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FirstName",
                        "Surname",
                        "Title"});
            table1.AddRow(new string[] {
                        "Tomasz",
                        "Bien",
                        "Mister"});
#line 4
 testRunner.When("User creates a contact with following data", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "MinPrice",
                        "MaxPrice",
                        "MinBedrooms",
                        "MaxBedrooms",
                        "MinReceprionRooms",
                        "MaxReceprionRooms",
                        "MinBathrooms",
                        "MaxBathrooms",
                        "MinParkingSpaces",
                        "MaxParkingSpaces",
                        "MinArea",
                        "MaxArea",
                        "MinLandArea",
                        "MaxLandArea",
                        "Description"});
            table2.AddRow(new string[] {
                        "1000000",
                        "4000000",
                        "1",
                        "5",
                        "0",
                        "2",
                        "1",
                        "3",
                        "1",
                        "2",
                        "1200",
                        "2000",
                        "10000",
                        "20000",
                        "RequirementDescription"});
#line 7
 testRunner.When("User creates following requirement with given contact", ((string)(null)), table2, "When ");
#line 11
 testRunner.Then("User should get OK http status code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Residential sales requirements")]
        [Xunit.TraitAttribute("Description", "Negative - Save requirement to DB without contact, all detailed fields fulfilled")]
        public virtual void Negative_SaveRequirementToDBWithoutContactAllDetailedFieldsFulfilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Negative - Save requirement to DB without contact, all detailed fields fulfilled", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "MinPrice",
                        "MaxPrice",
                        "MinBedrooms",
                        "MaxBedrooms",
                        "MinReceprionRooms",
                        "MaxReceprionRooms",
                        "MinBathrooms",
                        "MaxBathrooms",
                        "MinParkingSpaces",
                        "MaxParkingSpaces",
                        "MinArea",
                        "MaxArea",
                        "MinLandArea",
                        "MaxLandArea",
                        "Description"});
            table3.AddRow(new string[] {
                        "1000000",
                        "4000000",
                        "1",
                        "5",
                        "0",
                        "2",
                        "1",
                        "3",
                        "1",
                        "2",
                        "1200",
                        "2000",
                        "10000",
                        "20000",
                        "RequirementDescription"});
#line 15
 testRunner.When("User creates following requirement without contact", ((string)(null)), table3, "When ");
#line 18
 testRunner.Then("User should get BadRequest http status code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ResidentialSalesRequirementsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ResidentialSalesRequirementsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
